### ISSUE TITLE
PennyLane has no attribute 'MottonenStatePreparation'

### ISSUE THREAD

**Issue by sassan72** [PennyLaneAI/pennylane#1003]
qml.MottonenStatePreparation(x, wires=[1, 2, 3])
AttributeError: module 'pennylane' has no attribute 'MottonenStatePreparation'

**Comment by josh146** [comment]
Hi @sassan72, I believe it should be `qml.templates.MottonenStatePreparation`. Can you give that a go and let me know if it works?

**Comment by sassan72** [comment]
it worked. i am going to encode a dataset with 8 features with Mottonen state preparation. Based on Mottonen's paper, i need 3 qubits. i used thid 'qml.templates.MottonenStatePreparation(x, wires=[1, 2, 3])' for encoding. But i got this error: 
raise ValueError("'state_vector' has to be of length 1.0, got {}".format(norm))
ValueError: 'state_vector' has to be of length 1.0, got 35.146891102531455

should the input x be normalized before using Mottonen method?

**Comment by josh146** [comment]
@sassan72, I'm glad to hear that it worked! Since the original issue has been resolved, I will close this GitHub issue.

For your second question, can I direct you to open up a thread on our [discussion forum](https://discuss.pennylane.ai/) for your second question? While GitHub is a good avenue for letting the development team know about bugs and feature requests, the discussion forum is better suited to questions about using PennyLane for quantum machine learning 🙂

**Comment by sassan72** [comment]
thanks
