### ISSUE TITLE
deprecation warning when importing from collections

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1043]
Upon running tests, I often get the warning:

```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from collections import Sequence
```

Especially if we want to support Python 3.9, we should fix this everywhere in the code. One such location is [in `vqe/vqe.py`](https://github.com/PennyLaneAI/pennylane/blob/c1bfc27d6e191f034ff79ad01cfad2416198ecdc/pennylane/vqe/vqe.py#L19).

**Comment by kessler-frost** [comment]
Hi @albi3ro,

I checked everywhere for this specific collections warning and it seems that the `vqe/vqe.py` file is the only one where `collections` was used inappropriately instead of `collections.abc` to import `Sequence` or `Iterable`. In all of the other places, the use of `collections` seemed correct. I wanted to ask whether you encountered any other deprecation warning that requires fixing?

Thank you

**Comment by albi3ro** [comment]
Thanks for checking.  

I guess I've just seen that error so many times it feels like its everywhere.

**Comment by kessler-frost** [comment]
Got it. So should I just create a PR for that change? It's actually pretty small.
