### ISSUE TITLE
Tensorflow is always imported on initial import, even if never used

### ISSUE THREAD

**Issue by Thenerdstation** [PennyLaneAI/pennylane#1101]
When PL is imported and TensorFlow is installed, PL will always import it, even if the user never uses it.

It's minor, but it makes the initial import time a lot longer. We should consider finding a way to only import TF if the user uses a TF device or uses a TF interface.

I believe these also apply the PyTorch and Jax.

**Comment by josh146** [comment]
💯 

On my laptop the TF import time is very noticeable.

**Comment by josh146** [comment]
would be great to have this available prior to the next PL release :D

**Comment by josh146** [comment]
I've tracked this down: the offending module is `pennylane.qnn`. I'm not sure there is a workaround for this without changing existing behaviour; here, we _need_ to import TensorFlow at the module level, since `KerasLayer` inherits from `tf.keras.Layer`. I cannot think of a way of patching this without messing up the documentation or other UX pitfalls.

The cleanest, safest thing to do is simply remove the `import pennylane.qnn` from `pennylane/__init__`.

This means that you can no longer do

```python
import pennylane as qml
qml.qnn.KerasLayer
```

Instead you need to do

```python
import pennylane as qml
import pennylane.qnn  # tf and torch imports happen here
qml.qnn.KerasLayyer
```

but it is very clean and simple, avoids crazy monkeypatching, and allows docs and docstrings to all show correctly.

**Comment by Thenerdstation** [comment]
I think your first solution is the correct one. Updating docs is relatively easy vs metaprogramming.

**Comment by trbromley** [comment]
I'm all for the simple solution, but have a bit of reluctance because it's a breaking change - `KerasLayer` is fairly commonly used on the forum so we might anticipate questions going forward from users on why their code isn't working.

Is there a way we could give a warning if users try
```python
import pennylane as qml
qml.qnn.KerasLayer
```
?

**Comment by co9olguy** [comment]
This is a classical case for a one-release-cycle deprecation warning

**Comment by co9olguy** [comment]
@trbromley just wanted to make sure you saw the suggestion above about a deprecation warning, since it seems #1162 is just ripping the bandaid off
