### ISSUE TITLE
Gate decomposition and observables under default.qubit in tape mode

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#1108]
The `default.qubit.autograd` device, which seems to be used whenever `default.qubit` is requested in the most recent versions of PennyLane, does, contrary to the old `default.qubit` device, no longer automatically decompose gates it does not support and instead fails with a `pennylane._device.DeviceError: Gate XXX not supported on device default.qubit.autograd`.

This breaks the execution of QNodes with custom gates that are not natively supported on `default.qubit.autograd` but used to work on the old `default.qubit` because they have a valid decomposition into gates supported by `default.qubit.autograd` and `default.qubit`.

Can this automatic gate decomposition functionality please be restored?

**Comment by cvjjm** [comment]
Maybe a separate issue but close enough to this one to be mentioned here: `default.qubit.autograd` from the current `master` also does seem to no longer support any custom observables apart from the official PennyLane ones. The old `default.qubit` device allowed (and correctly handled) all observable classes derived from `Observable` as long as they declared `._matrix()` and `.deagoalizing_gates()`.

**Comment by co9olguy** [comment]
Hi @cvjjm, thanks for submitting the issue.
While we dig into it, one possible solution is for you to explicitly set the differentiation method to be parameter-shift? This should force PL to use the parent `default.qubit` device instead of the autograd device

**Comment by cvjjm** [comment]
Yes, that is a workaround, but I would have to set that in a few dozen places 8and moreover in a backward compatible way), so I think I will rather wait with upgrading to the latest PL until `default.qubit.autograd` learns how to decompose gates unless you tell me that you don't plan to enabled decomposition in those devices :-)

What is the reason for why `default.qubit` is no longer `default.qubit` but now points to `default.qubit.autograd`? Wouldn't it make sense to give users `default.qubit` if they asked for it?

**Comment by co9olguy** [comment]
> What is the reason for why default.qubit is no longer default.qubit but now points to default.qubit.autograd? Wouldn't it make sense to give users default.qubit if they asked for it? There are reasons for why one may want to use default.qubit instead of default.qubit.autograd that have nothing to do with the diff_method

You might even be able to guess why we did this :wink: 
`default.qubit` uses parameter-shift by default, but is a simulator. It is much quicker to use backprop or adjoint methods to compute gradient for simulators. After many interactions with users, it is clear that many users use `default.qubit` as, well, their default. In an overall effort to make the PennyLane experience as fast as possible for as many users as possible, we decided to use backprop as the diff method if it is compatible and nothing else was explicitly specified.

Anyway, I can see two relatively simple solutions to the issue you raised:
- we make sure that child devices properly handles decompositions, in particular for non-built-in gates (admittedly this is a blind spot for us, since if we are ever interested in a new gate, we just add them in to the codebase)
- we introduce something like `default.qubit.param_shift` or maybe a new keyword argument like `strict` to `qml.device` so that users can easily take control if they want a very specific version of a device

**Comment by josh146** [comment]
Thanks @cvjjm for catching this!

> we make sure that child devices properly handles decompositions, in particular for non-built-in gates (admittedly this is a blind spot for us, since if we are ever interested in a new gate, we just add them in to the codebase)

This is actually surprising to me - `default.qubit.autograd` simply inherits from `default.qubit` while simply swapping out numpy for autograd numpy, so decompositions defined for `default.qubit` should continue to work fine.

I would say that this is actually a bug, since this should be working.

**Comment by cvjjm** [comment]
I see why you would want to supply a faster simulator, but I still think it is not nice to return a device other than then one the user requested. There are many other reason for why a user may want to use a specific device, among them: (i) Testing whether their gate decompositions are correct. (ii) Counting the number of circuit evaluations that would be needed on a real device. (iii) Comparing or benchmarking different devices against each other... When I ask for `default.qubit` I expect to get `default.qubit`. If someone wants a fast simulator they should have to explicitly specify this, I think. I don't think that indroducing `default.qubit.param_shift` or a `strict` keyword would be a good fix, because then I can just go through the code base and add `diff_method='paramter-shift'`.

I also dug deeper into the other issues mentioned above and found the following: The decomposition _does_ work, my my impression that it didn't was caused by a recursion depth issue, which I know how to solve, by increasing the decomposition recursion depth. It also turned out that non standard observables, while I remember they were supported in the old days, have not been supported for some time now (I checked back to 0.12.0) and it is not something I need or which I think absolutely needs to be supported, so both the original issues are solved :-) I am still unhappy about getting another device than the one I asked for :-)

**Comment by trbromley** [comment]
Thanks @cvjjm! You make a good "Explicit is better than implicit" point.

For me, the motivation of the current "swap out device" approach is to make sure users get the fastest possible device without having to worry about the subtleties of what `default.qubit` vs `default.qubit.autograd` entails. Advanced users can then be more specific about which device to select. I guess a compromise could be to add a warning when the device is changed behind the scenes, but I am not too much of a fan of warnings which pollute and could also be confusing.

**Comment by cvjjm** [comment]
I am not your only user, so don't give too much weight to my opinion. I also tend to have pretty strong opinions about these kind of things so don't be surprised if I use strong words when expressing my view :-)

I think it is a terrible idea to break peoples code in a hideouts way. More and more people publish the code underlying their publications and they do normally not specify the versions of all the libraries with which this code is meant to run. When simply changing the meaning of `default.qubit`, code that made assumptions about the wokring of the device (think for example code counting the number of circuit evaluations that are necessary to compute something on hardware with parameter shift rule) breaks. It moreover breaks just producing different results and not throwing an exception. This is terrible. Don't do it.

I don't see why you would not simply loudly advertise that there is now a much faster device available than `default.qubit` (especially since which diff_method is fastest will also depend on the concrete circuit). I think people will take notice and use this device when they need performance.

**Comment by mariaschuld** [comment]
To tune in here: This is a question of what you want to achieve with a library. One - if not the most important - goal of PennyLane is to make it easy for users to start off with quantum differentiable programming. Naturally, one of its main tasks is therefore to take the weight of decisions from user's shoulders.

If we tell our users "should you work in tensorflow, then backpropagation is at the moment the fastest differentiation method so you have to choose the default.qubit.tf device that is end-to-end diffable, but you may not sample when you use the device", you need to be quite an expert to parse this and 95% of the users would probably be lost (or blindly use whatever their favourite demo shows, wondering why things are slow when they do something else). 

So there is a fine balance between providing transparent behaviour under the hood, and making things easy and fast. We decided after long deliberation in this case we want to cater for the 95% of users, necessarily sacrificing a bit of consistency. 

Having said that, the idea of just running a device that the user did not instantiate is not a solution we are totally happy with either, and we hope to find a better one soon...

**Comment by josh146** [comment]
>  The decomposition does work, my my impression that it didn't was caused by a recursion depth issue, which I know how to solve, by increasing the decomposition recursion depth. It also turned out that non standard observables, while I remember they were supported in the old days, have not been supported for some time now (I checked back to 0.12.0) and it is not something I need or which I think absolutely needs to be supported, so both the original issues are solved :-)

Great to hear @cvjjm!!

> I am still unhappy about getting another device than the one I asked for :-)

I suggest we close this issue, and re-open a new one to directly discuss swapping out devices, based on the content of https://github.com/PennyLaneAI/pennylane/issues/1108#issuecomment-785755285.

>  I still think it is not nice to return a device other than then one the user requested. 
>
> More and more people publish the code underlying their publications and they do normally not specify the versions of all the libraries with which this code is meant to run. When simply changing the meaning of default.qubit, code that made assumptions about the working of the device breaks. It moreover breaks just producing different results and not throwing an exception. This is terrible. Don't do it.

I agree to an extent; my biggest worry with this change is that the device object used to execute the QNode is _not_ the same object as the device the user is carrying around. This is definitely something I would like to fix, and causes issues with tracking the number of executions.

In terms of the underlying devices, though, I think it's worth pointing out though that `default.qubit.autograd` and `default.qubit.tf` inherit 99% of the same logic as `default.qubit`; the only changes are:

* Using autograd/TF rather than NumPy, and
* Overwriting the `_get_unitary_matrix` method to extract a unitary using the required autodiff framework.

As a result, `default.qubit.autograd` and `default.qubit.tf` only differ in about ~15 lines of code! As a result, we would like to move towards a place where `default.qubit.autograd`, `default.qubit.tf`, and `default.qubit` are all the **same device**; `default.qubit` just supports backprop using autograd or TF _in addition_ to the existing parameter-shift support.

So thinking of these as the 'same' device:

- this change is more about changing the default diff method, rather than the device
- the fact that we are actually 'swapping out the device' is a byproduct of this device merger not being fully complete.

To fix the sneaky device swap, I suggest we work to better merge `default.qubit.autograd`, `default.qubit.tf`, and `default.qubit`.

> I don't see why you would not simply loudly advertise that there is now a much faster device available than default.qubit (especially since which diff_method is fastest will also depend on the concrete circuit). I think people will take notice and use this device when they need performance.

The problem is one of communication, as @mariaschuld noted above! Backprop only works if the device framework and interface match, _and_ expectation values are exact; simply wanting to estimate the gradient using a finite number of shots requires a fallback to the parameter-shift rule.

**Comment by cvjjm** [comment]
Knowing now that you want to move in a direction where the `default.qubit.xxx` devices all become "the same device" the change in behavior suddenly starts to make a lot more sense!

**Comment by trbromley** [comment]
Thanks @cvjjm for this useful feedback!

**Comment by cvjjm** [comment]
Yes, let's close this one.
