### ISSUE TITLE
Feature Request: qml.Hermitian to accept Scipy sparse array

### ISSUE THREAD

**Issue by santoshkumarradha** [PennyLaneAI/pennylane#1116]
Hi,

It would be a great memory and life saver if `qml.Hermitian(ham.toarray(),wires=range(2))`  could accept sparse Scipy array than actual 2^n x 2^n matrix for ham.

**Comment by josh146** [comment]
Hi @santoshkumarradha, this is a great idea. Currently, when you use `qml.Hermitian(H)`, the eigenvalues and eigenvectors of H are computed under-the-hood:

https://github.com/PennyLaneAI/pennylane/blob/5095918c03da1b82bbdbe94055d7846244127dc0/pennylane/ops/qubit.py#L1915

However, we could simply use [`scipy.sparse.linalg.eigsh`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html) if the provided matrix is sparse rather than dense.

If you would like to contribute, this would be a great first issue for a PR!

**Comment by Yash-10** [comment]
Hello @josh146,

I was trying to implement this. I found a line in the description of [`scipy.sparse.linalg.eigsh`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html) which says:

> The number of eigenvalues and eigenvectors desired. k must be smaller than N. It is not possible to compute all eigenvectors of a matrix.

Since the current implementation of `numpy.linalg.eigh` assumes a dense matrix, it could compute all the `n` eigenvalues and eigenvectors, but it seems that for sparse matrices, we could only find upto `n-1` eigenvalues and eigenvectors.

Hence, I suspect this fix might involve considerable amount of changes (including changes in the tests to handle sparse matrices). So could you let me know if allowing sparse matrices would really be a good choice (since the changes might not even be feasible), or am I missing something?

Thanks!

**Comment by santoshkumarradha** [comment]
@Yash-10 that is indeed correct, an outcome of ARPACK. A temporary (although not best) fix might be to convert it to `.toarray()` right before calculating eigenvals and use `np.linalg.eigvals()`. Although this won't speed up the calculation of eigvals, this might at least partially support the use of sparse matrix as input.

**Comment by Yash-10** [comment]
Thanks for your comment @santoshkumarradha !

> A temporary (although not best) fix might be to convert it to .toarray() right before calculating eigenvals and use np.linalg.eigvals(). Although this won't speed up the calculation of eigvals, this might at least partially support the use of sparse matrix as input.

I think due to the way `scipy.sparse` works, converting it into a numpy array might still yield numerical inaccuracies since it is tailored for sparse ones while `numpy` assumes dense matrices. Infact, the inaccuracies might very well go beyond tolerance and hence unacceptable for use.

Hence I am unsure of a way to solve this.

**Comment by josh146** [comment]
@Yash-10; this is a good point, I was unaware of the eigenvalue/eigenvector restrictions when I made my original comment.

If possible, we should avoid an implementation where a sparse Hamiltonian is converted into a dense matrix, since this likely negates the advantages of keeping the Hamiltonian sparse in the first place!

There are two ways I can see of doing this:

- Computing (dense) eigenvectors and eigenvalues directly from the sparse representation -- however, as you note above, this is not possible with `scipy.sparse`.

- Alternatively, computing expectation values *directly* via `<psi|H|psi>`, where both the statevector `|psi>` and the Hamiltonian `H` are sparse. However, this approach requires a sparse statevector simulator, which we do not currently have in PennyLane; this is being worked on as part of #1185.

**Comment by santoshkumarradha** [comment]
Closed with Pennylane 0.16.0
