### ISSUE TITLE
Allow BasisEmbedding to be applied at any point in a circuit

### ISSUE THREAD

**Issue by co9olguy** [PennyLaneAI/pennylane#1201]
The functionality of `BasisEmbedding` and `BasisStatePreparation` seems to do the same thing. Favouring a cleaner codebase, and recognizing that the term "embedding" might be better suited for floating-point-valued data, we should consider removing `BasisEmbedding`

**Comment by co9olguy** [comment]
@mariaschuld might have some thoughts here

**Comment by mariaschuld** [comment]
In principle I am not against keeping the duplicity, since the embeddings may get different functionality over time, for example checking the inputs more rigorously, or not having restrictions of being the first ops in a circuit (since a feature map could also be applied to a non-zero initial state, and a kernel estimator may require the evaluation of inverse embeddings after other operations). Also, it is easier to keep a gallery of embeddings, which users will look at when they need to encode data.

**Comment by SaashaJoshi** [comment]
Would it be a good idea to keep one of the two functions as first-only (refer to Issue#1191) and transform the other to be applied at any depth in the circuit? 
I guess @mariaschuld says the same.

**Comment by mariaschuld** [comment]
@co9olguy did we convince you, or shall we keep this issue open?

**Comment by co9olguy** [comment]
Thinking about it, I think it does make sense to be able to consider embeddings to take place at any place in a circuit, not just the start, whereas state preparations would be restricted to be the beginning
