### ISSUE TITLE
Raise exception or warning when `qml.adjoint` is used on operation list instead of function.

### ISSUE THREAD

**Issue by dwierichs** [PennyLaneAI/pennylane#1336]
The newer `qml.adjoint` function does not have any effect when acting on operation lists like in the following example:
```python
params = list(range(4))
qml.adjoint(qml.templates.AngleEmbedding(params))
```
Users might try this, because it worked like this with `qml.inv` which `qml.adjoint` is replacing. Therefore, we should raise
an exception whenever this is attempted by checking for the input to be `callable`. Alternatively, a warning could be raised, but 
the behaviour differs fundamentally from the expected, an exception seems more appropriate.

**Comment by mariaschuld** [comment]
Is there no way to make the above work?  I remember that there was a good reason, but it would be so nice and intuitive! 

For example, the transform could make a function for the gate?

**Comment by josh146** [comment]
> Is there no way to make the above work? I remember that there was a good reason, but it would be so nice and intuitive!

Unfortunately I don't think so, since Python always evaluates 'inside out' - it will evaluate `qml.templates.AngleEmbedding(params)` before any `adjoint logic is ever executed.

This is one of the reasons that `qml.inv()` was so nasty internally; it was performing a lot of queuing hacks to make the above work. In fact, `qml.inv()` showing up in the 'files changed' tab in a recent refactor was one of the reasons it got marked as priority for removal 😆 

> but it would be so nice and intuitive!

My hope is that with good documentation and consistent usage, the above _does_ become intuitive to PL users. The same way that `qml.grad(fn)(params)` has become intuitive 🙂

**Comment by co9olguy** [comment]
@josh, by "the above" do you mean something like 
```
qml.adjoint(qml.templates.AngleEmbedding)(params)
```
?

**Comment by josh146** [comment]
@co9olguy, yes, exactly. This is the UX that is consistent across other functional libraries, c.f. both Autograd and JAX, and slowly also TF, since it results in very intuitive composability due to the transform acting on _functions_, rather than objects:

```python
>>> autograd.grad(fn)(params)
>>> jax.vmap(fn)(batched_params)
>>> tf.function(fn)(tensor)
>>> np.vectorize(fn)(params)
```

It is also a UX that is not out of place in PennyLane (`qml.grad(fn)(params)`, `qml.draw(qnode)(params)`).

Here, we just need to get used to treating quantum operations _themselves_ as (quantum) functions, rather than objects.

**Comment by mariaschuld** [comment]
Just a crazy thought - could we turn operations into functions or wrap them in functions?
