### ISSUE TITLE
Change `default.qubit` to compute the inner product for `qml.Hermitian` 

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#1344]
The `QubitDevice` class provides a [standardized way for computing the exact expectation value](https://github.com/PennyLaneAI/pennylane/blob/8f8205f18044fb8479fe50f040d6db7aa7e78f44/pennylane/_qubit_device.py#L739) of a specific observable. For observables that are not diagonal in the computational basis, diagonalizing gates are applied at the end of the requested circuit. To compute the expectation value of the observable, the probability distribution of the computational basis states after executing the circuit and the eigenvalues of the observable are used.

When using `qml.Hermitian`, this method, diagonalizing the matrix of the observable. This can be a costly operation.

As an alternative method, we would like to change the `expval` method such that the inner product `<psi|H|psi>` is computed where `H` is the observable. For now, we'd like this change to be made in `DefaultQubit`. Worth exploring the best way of implementation and if it would be worth having this change in `QubitDevice` directly.

**Comment by josh146** [comment]
To add some context:

- The current method was chosen because it is hardware compatible.
- On simulators, there is very little overhead for statistics of Pauli words
- However, the overhead for `qml.Hermitian` is significant, because diagonalizing it requires computing the eigenvalues of a large dense matrix.

Therefore, it is worth modifying `default.qubit` to avoid diagonalization in the special case of `qml.Hermitian`, for a very nice short-term gain.

@antalszava, I'm not sure if it is worth making this change in `QubitDevice` (yet), since `QubitDevice` is currently inherited by both software _and_ hardware devices that still need the diagonalization to be performed.

**Comment by antalszava** [comment]
Yep, good point, was also considering that! Though this is a method specific for state vector simulators, so maybe it could be more general? 🤔 we have the condition `if self.shots is None`

**Comment by albi3ro** [comment]
Was closed by PR #4866
