### ISSUE TITLE
Add support for returning raw samples from QNodes

### ISSUE THREAD

**Issue by josh146** [PennyLaneAI/pennylane#1431]
Currently in PennyLane, if you want to return samples from a QNode, you must specify the observable to sample. For example,

```python
@qml.qnode(dev)
def circuit():
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    return qml.sample(qml.PauliZ(0))
```

When requesting samples of observables, the `QubitDevice` class will extract the raw samples from the device (for qubit-based devices, these are the computational basis samples 0 or 1), and post-process them according to the observable in question. In this example, they will be post-processed and transformed into an array of -1 and 1.

It would be great to add support for returning the raw, computational basis samples from a device, without requiring an input observable. From a UI point of view, this could be done one of two ways:

1. `return qml.sample()`, with no observable, results in raw device samples being returned
2. A new measurement function, `return qml.basis_samples(wires=[0, 2])`, is made available, similar to `qml.probs` and `qml.state`.

To implement this functionality, the following changes must be made:

1. In `measure.py`, a new measurement function is added (or, `qml.sample` is modified), which returns `MeasurementProcess(Sample, obs=None, wires=wires)`.

2. In `QubitDevice.statistics`, logic is added to handle this new measurement class, and the devices raw samples (`self._samples`) are returned.

**Comment by Jaybsoni** [comment]
Hi Josh, thanks for the feature request ! I had a chance to look over some of the source code last night and I just wanted to confirm my understanding and run some questions by you before I start implementing a solution. (As this is part of the technical assessment, feel free to not answer some of my questions if you want me to figure them out myself.) 

Below I describe my current understanding of the process (please correct me if I am wrong):

- The code above instantiates and Qnode object
- The line `qml.sample(qml.PauliZ(0))` returns a MeasurementProcess object with return type Sample and observable Pauliz(0)  
- When `circuit()` is called, the Qnode object is executed (line 582 of qnode.py)
- We are interested in `self.qtape.execute(device)` (line 598 of qnode.py)
    - `self.qtape` is a QuantumTape instance (or one of its subclass instances) 
    - The call will run the device-specific execute method (in this case I look at _qubit_device.py)
- The local execute method of the QubitDevice class is called (_qubit_device.py) 
- The raw samples are generated and stored in `self._samples` (line 196 of _qubit_device.py) 
- Then the statistics method is called to post process these raw samples
- In this case the statistics method calls the `self.sample` method to perform the post processing and return the results 

Below I describe my current understanding of the feature request(again, correct me if I am wrong): 

- We want to add functionality such that users can get device specific raw samples. By raw samples, we mean the device specific native samples drawn from the hardware. 
- Currently an observable is a required argument in `qml.sample` in order to generate samples. 
- We wish to relax this requirement or implement a new function `qml.basis_samples` which can accomplish this goal

Here are some ideas I have to implement it: 

- I personally feel that augmenting `qml.sample` is a better approach because it seems more intuitive to use. 
- As mentioned in the request I would augment `sample` in measure.py to return a MeasurementProcess object with return type Sample and obs=None. 
- Then I could look into _qubit_device.py and augment `sample` by adding a check to see if the observable is a None type. If so I would just return self._samples (binned according to specifications)  

Questions: 

- In the two approaches proposed in the feature request, the direct call `qml.sample()` does not require information about wires whereas the `qml.basis_sample` call explicitly adds them. So is this information required? (i.e can I implement the `qml.basis_sample` without the wires keyword argument? Or vice versa will I need information about wires if I choose to augment `qml.sample`?) 
- In the `qml.basis_sample` call the keyword argument wires is given as: `wires=[0,2]`. It seems that the 1 index is missing. Is this function somehow summing together samples with the same first and third qubit but varying second qubit values to give some kind of marginal sample set? Is this functionality also required if I choose to augment `qml.sample`? 
 
I look forward to working on this feature request over the next two weeks. 
Thanks !

**Comment by josh146** [comment]
Hi @Jaybsoni!

Your understanding is spot on 🙂 

> By raw samples, we mean the device specific native samples drawn from the hardware.

Just to expand a bit, the reason I avoid saying 'computational basis samples' is that in PennyLane we _also_ support photonics/continuous-variable devices, that return samples from the Fock space.

> I personally feel that augmenting qml.sample is a better approach because it seems more intuitive to use.

Yes, I lean towards this as well. The main reason I also suggested a separate `qml.basis_samples` is that, since it would be self-contained, it might be easier to implement. But using the existing `sample` function would be nicer for the user-interface!

> In the two approaches proposed in the feature request, the direct call qml.sample() does not require information about wires whereas the qml.basis_sample call explicitly adds them. So is this information required?

Good question!

In current usage when using `qml.sample`, the wires that are being sampled are extracted from the observables. For example,

```python
m = qml.sample(qml.PauliZ(0) @ qml.PauliZ(2))
```
would result in `m.wires= Wires([0, 2])`. Without a specified observable, there is no wire information.

So we have two options:

- If we allow `return qml.sample()`, we must assume we are sampling _all_ wires.
- If we also allow for `qml.sample(wires=[3, 6])`, this then allows for returning raw device samples from a subset of the available wires.

> In the qml.basis_sample call the keyword argument wires is given as: wires=[0,2]. It seems that the 1 index is missing. Is this function somehow summing together samples with the same first and third qubit but varying second qubit values to give some kind of marginal sample set? Is this functionality also required if I choose to augment qml.sample?

My intention here was simply that the samples from the second qubit are not returned 🙂 This would be the equivalent of simply 'dropping' that row from the returned NumPy array.

This might be a useful feature if you have a large remote device (say, O(100) qubits), but are only interested in returning samples from a subset of wires --- it avoids the need to communicate samples from _all_ wires from the remote device.

**Comment by Jaybsoni** [comment]
Hi @josh146, 

Thanks for the clarification! I have begun implementing a solution. Here is a quick status update for you:
(you can find the code at: https://github.com/Jaybsoni/pennylane/tree/raw_samples)   

**Updates:** 
- Updated `sample(op)` in measure.py:
      -  to accept `op=None` and added optional argument `wires`
      - updated documentation to describe the new functionality
- Updated `QubitDevice.sample()` in _qubit_device.py 
      - to check for observables which have type `MeasurementProcess` (this happens when no observable is provided) 
      - then return `self._samples` 
      - also added functionality to check if `wires` were provided, in this all other wires' sample values are dropped before returning the samples 

**Here are some code snippets and the results:** 

In the following image I demonstrate the `qml.sample()` with no observable functionality:
![1](https://user-images.githubusercontent.com/21964864/123907534-11871100-d944-11eb-81f0-e0fd43e18f9f.png)

In the following image I demonstrate the `qml.sample(wires=[])` with wires provided functionality:
*I add lines to print the raw samples so that they can be validated. The call would actually only produce the second array with no additional print statements* 
![2](https://user-images.githubusercontent.com/21964864/123907539-13e96b00-d944-11eb-999e-d3d61285f120.png)

**To Do:**
- Update unit tests for the code changes and verify that the test suite runs with no errors 
- Found a bug with plotting circuits when no observable is provided **but** wires are provided 
- Add additional comments and documentation as needed 

Here is a quick image of the error I have encountered: 
![3](https://user-images.githubusercontent.com/21964864/123908030-d76a3f00-d944-11eb-9cb0-a9931d79ce3e.png)

Feel free to explore the code I have written so far and provide any comments on my implementation. I haven't made too many changes and I have tried to stay consistent with the style of code in the repo. I will keep you updated as I continue to work on this feature! 

Thanks!

**Comment by josh146** [comment]
Hi @Jaybsoni, awesome to hear!

Could I get you to open a work-in-progress PR here in the PennyLane repo with your branch? Simply prepend the title with `[WIP]` 🙂 

That way, if you have any questions or issues, you can simply leave a comment at the specific code line and tag me in it.

**Comment by Jaybsoni** [comment]
Hey @josh146, I have opened a work-in-progress PR:  #1441

I don't think I have any specific questions for you yet. I want to spend some more time looking through the error messages before I reach out for help.

I do have a clarification question: 
- I have only updated the sample code in the `QubitDevice` class, but I think you want this update to apply to any device that pennylane can interface with (Qubit, CV, or other). If this is the case, do you have a list of all such device types and a class implementation for each type?

**Comment by josh146** [comment]
> I have only updated the sample code in the QubitDevice class, but I think you want this update to apply to any device that pennylane can interface with (Qubit, CV, or other). If this is the case, do you have a list of all such device types and a class implementation for each type?

While all qubit devices inherit from `QubitDevice`, all other devices (including the CV devices) inherit from the parent `Device` class 🙂 

For example:

- `default.gaussian`, a Gaussian photonic simulator built-in to PennyLane, inherits from `Device`
- `strawberryfields.fock`, a Fock-space photonic simulator provided by the PennyLane-SF plugin, inherits from `Device`.

I don't think `default.gaussian` has the capability to return Fock space samples, but `strawberryfields.fock` does.

However, this may be a lot more work, since it would require PRs to the plugin repository!
