### ISSUE TITLE
Interfaces and documentation introduction section

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#1565]
To find the interfaces in the introductory documentation, you have to click on "Gradients and Training", which isn't immediately obvious to me.

I propose we have one section for "Gradients and Training" and a separate section for "Interfaces", so you can quickly get to information on the different interfaces.

**Comment by josh146** [comment]
@albi3ro this one was somewhat intentional! It used to be called 'Interfaces' a while ago, and @mariaschuld and I spent a while discussing the rename.

The idea being that, a new user might know that they want details on gradients or training, so will look for this in the ToC. Since 'interface' is PL-specific jargon, seeing that phrase in the ToC wouldn't mean anything to them.

In fact, I'm thinking, if possible, if we can go even further, and reduce usage of 'interface' across our docs and demos. As part of the current 'differentiable batch-execute' story, I just realized the other day that it makes the `interface="autograd"` keyword argument redundant 🙂  Using `qml.math` and some magic, it's now possible to determine automatically the interface by inspecting the tape.
