### ISSUE TITLE
Backprop for density matrix simulation

### ISSUE THREAD

**Issue by shukob** [PennyLaneAI/pennylane#1694]
### Feature details

I would like to perform backprop on the `default.mixed` device, but that seems not implemented.

### Implementation

`mixed` version of autodiff backends: `default_mixed_{autograd, jax, tf, torch}`, should be implemented and set as `passthru` devices for `default.mixed`.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by CatalinaAlbornoz** [comment]
Hi @shukob, thank you for this feature request! It looks like something we should definitely work on.

**Comment by josh146** [comment]
Hi @shukob! Yes, this is definitely something that would be great to have in PennyLane. We have an existing issue to address this, with some more context if you are interested to take a look: https://github.com/PennyLaneAI/pennylane/issues/1528.

Since this is covered by #1528, do you mind if we close this issue?

**Comment by shukob** [comment]
@josh146 Thanks for pointing me #1528. Sorry about not finding the issue by myself. I do not mind closing this.
