### ISSUE TITLE
Problem caused by .num_params no longer being a static property

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#2099]
### Feature details

In 0.20.0 `.num_params` is no longer a static property but a regular instance property and this breaks a lot of my code.

For instance without this information being available from the class it is no loner possible to auto generate parameter tensors of appropriate size.

It is understandable that for some gates the number of parameters depends on the instance, but for the vast majority of gates the number of parameters _is_ a property of the class.

Can `.num_params` please be made a static property again for those Operations where this is possible?

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

**Comment by cvjjm** [comment]
A concrete example consider `SWAP`. This may be relevant for @mariaschuld 's work on refactoring the Operation class.

**Comment by mariaschuld** [comment]
I think we could do this for backwards compatibility: we could just add this as an optional attribute that stores the value which gets checked when overwriting the instance property. 

The important part is that it is not a requirement any more, so no code should expect this attribute to be there.

**Comment by cvjjm** [comment]
The information is still there and it is also still stored in the code of the Operator class, but it is currently no longer accessible unless one has an instance. But one cannot create an instance if one doesn't know how many parameters an Operation has...

**Comment by mariaschuld** [comment]
Yes. I still want to emphasize that one should move away from patterns that create operator instances automatically, unless you are in a very specific setting. Since the operator library grew so much, the signatures and requirements start to diverge more and more, and we do not want to encourage this...

**Comment by cvjjm** [comment]
I don't want to create Operator instances automatically I want to continue to be able to write code that lays out circuits composed of gates specified by the user and for that the Operator class needs to keep providing some basic information about the gates.

Having to create and then maintain a giant lookup table just so my code knows that SWAP has zero parameters and RY has one just cannot be the right way to solve this...

**Comment by mariaschuld** [comment]
Hmm, I am still not sure I understand your use case. Surely when I use a gate, I have to look up the signature to see what it expects? Many many gates do not just take parameters, but the signatures are really diverse by now. So inferring what args and kwargs to create it with is dangerous... but once I have to know the signature, I can also look up the number of parameters...

Another issue is that the number of parameters is not necessarily the number of args! Think of templates where the user provides some inputs, and in the `__init__` method we process the inputs and extracts what we feed into the main operator class as args - which will then become stored in `op.parameters`. 

I'm also trying to understand precisely, because we have a plan to provide an `OpClass.shape()` method in all operators, which returns the shape or a list of shapes for trainable parameters that the operator depends on (not yet sure how this will be matched with user-provided arguments, but there are some ideas). The nice feature here is that the method can depend on hyperparameters like `n_wires` or `n_layers`, so it works for any operator. Currently the templates have this method.

**Comment by cvjjm** [comment]
I am insisting on this because no loner having this property available breaks various code I have in a non-fixable way. 

As a matter of fact I could programmatically deduce the number of parameter from the docstring of each class... But having to do that would be absurd :-) 

The number of parameters is kept in the code of each Operation. And it clearly is a property that is independent of the instance. Knowing the number of parameters is even a prerequisite for being able to create an instance. If this is not the definition of a class property then I don't know what. Why do you insist that it should be a property of the instance?

It is even much more of a class property than num_wires (which currently _is_ a class property). Further, I unfortunately cannot deduce the number of parameters/arguments from the function signatures of the class because in many cases the functions look like `def _matrix(cls, *params):`  and thus do not specify how many parameters there are.

It is also not that I ask for any new information to be provided. The number of parameters is already keep inside the code of each Operation. It is just not accessible anymore from the class but only from an instance, but I cannot create an instance without known the number of parameters... So ironically the information is still there it is just not accessible to anyone who doesn't already know the number of parameters and I want you to go back to a situation where it is :-)

**Comment by josh146** [comment]
I admit I know less of the nuances here than @mariaschuld, but perhaps we could go with a two-pronged approached?

That is, if an operation has a constant number of parameters, we use a class attribute directly:

```python
class SomeOperation(Operation):
    num_params = 5
```

but, if an operation has a dynamic number of parameters depending on other hyperparameters (such as wires), then we use the property

```python
class SomeOperation(Operation):
    @property
    def num_params(self):
        ...
```

**Comment by cvjjm** [comment]
Yes, this is exactly what I am proposing. In fact I think currently all Operations in PL are of the first kind.

**Comment by mariaschuld** [comment]
Again, I am not against re-adding the class attribute to some gates for backwards compatibility. For interest, the `num_wires` is only left as a class attribute because the `AnyWires` enum circumvents some of the issues we had with `num_params`, so there is no urgency to tidy this up.

But note that we 

a) will not guarantee that all operators define `num_params`, and 
b) do not guarantee that `num_params` is the same as the number of positional arguments that the operator takes to be constructed (since there is a conceptual difference between the number of parameters and the number of positional arguments that has naturally been used more and more when designing operators).

a) was artificially kept alive by ugly workarounds before (some ops like the Hamiltonian define an arbitrary number for `num_params` and then set it to the true value upon instantiation), while b) was never true, it just happens to work in many cases.  So we would add this attribute back where it makes sense as a convenience, but not as a design principle we limit operator design to in future. 

Hope that makes sense?

**Comment by cvjjm** [comment]
Yes, that makes perfect sense and it is perfectly ok if code that needs to know `num_params` before instantiating an Operation does not work with Operations that either do or cannot declare that property on the class level or whose number of positional parameters differ from `num_parame`. It just pained me to see the information still in the source code but inaccessible to anyone who didn't already know the answer :-)  

Do you have an example for an Operation that displays this conceptual difference between the number of parameters and the number of positional arguments? I would like to understand better what you mean here.

**Comment by cvjjm** [comment]
The PR is now "ready" all tests pass, just the coverage has decreased by 0.01%...

**Comment by mariaschuld** [comment]
Will merge asap and close this issue!
