### ISSUE TITLE
[BUG] QubitStateVector is decomposed even on devices that support it

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#2147]
### Expected behavior

QubitStateVector should not be decomposed and the output should be:
```
 0: ──╭QubitStateVector(M0)──╭┤ State 
 1: ──╰QubitStateVector(M0)──╰┤ State 
M0 =
[1. 0. 0. 0.]
```
This happens up to 0.19.1

### Actual behavior

QubitStateVector is decomposed
```
 0: ──╭C──╭C──╭┤ State 
 1: ──╰X──╰X──╰┤ State 
```
This happens in 0.20.0 an beyond.

### Source code

```python
import pennylane as qml
from pennylane.devices import DefaultQubit
from pennylane import numpy as np

dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev, diff_method='parameter-shift')
def circuit():
    qml.QubitStateVector(np.array([1.0, 0.0, 0.0, 0.0]), wires=[0, 1])
    return qml.state()

assert 'QubitStateVector' in dev.operations
print(qml.draw(circuit)())
```

### System information

```shell
As stated above the problem starts with 0.20.0.
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by josh146** [comment]
Thanks @cvjjm, this is a good catch. I know the cause here; in v0.20 we modified expansion behaviour such that:

> If the input to `QubitStateVector` is _trainable_, we decompose it using the Mottonen decomposition.

This allows us to make `QubitStateVector` differentiable, even on hardware. A current work around is to set the parameter of the `QubitStateVector` to be non-trainable:

```python
@qml.qnode(dev, diff_method='parameter-shift')
def circuit():
    qml.QubitStateVector(np.array([1.0, 0.0, 0.0, 0.0], requires_grad=False), wires=[0, 1])
    return qml.state()
```

which then avoids the decomposition:
```pycon
>>> print(qml.draw(circuit)())
 0: ──╭QubitStateVector(M0)──╭┤ State
 1: ──╰QubitStateVector(M0)──╰┤ State
M0 =
[1. 0. 0. 0.]
```

I'll need to think a bit more about this one, since this is expected behaviour in a sense; since the diff method is `parameter-shift`, and `QubitStateVector` was (originally) getting an array with `requires_grad=True`, it was being decomposed down into a form that supports the parameter shift rule.

**Comment by cvjjm** [comment]
Hardware devices cannot support `QubitStateVector` so that there I think expansion is expected. Is decomposition needed for differentiability even on simulator devices? If not, then the decomposition could continue happening only on devices that do not support `QubitStateVector ` natively?

**Comment by cvjjm** [comment]
To add some context: I cought this because I have a device that supports `QubitStateVector ` but does not support some of the gates resulting from the Mottonen scheme :-)

**Comment by josh146** [comment]
> Is decomposition needed for differentiability even on simulator devices? If not, then the decomposition could continue happening only on devices that do not support `QubitStateVector` natively?

A good question, because this is where the subtlety is :)

- On a simulator with `diff_method="backprop"`: this isn't required for differentiating `QubitStateVector`, all classical processing is end-to-end differentiable by nature.

- On a simulator with `diff_method="parameter-shift"`: this expansion _is_ required, because we don't have a parameter-shift rule for state preparation (but we _do_ have a parameter-shift rule after decomposing the state preparation into elementary gates).

> To add some context: I cought this because I have a device that supports `QubitStateVector` but does not support some of the gates resulting from the Mottonen scheme :-)

Ah got it! I suppose this raises a separate issue --- how should PennyLane behave if a device does not support gates arising from a _gradient_ decomposition.

We should probably catch this error, and raise something more useful, e.g.,

```python
GradientError: QubitStateVector does not support the parameter-shift rule on <device>. If you do not intend for it to be trainable, please set requires_grad=False
```

In the meantime, is setting `requires_grad=False` for your statevector array a workable solution?

**Comment by cvjjm** [comment]
> In the meantime, is setting requires_grad=False for your statevector array a workable solution?

Yes. Thanks!

**Comment by cvjjm** [comment]
Maybe the decomposition can then only be done when a gradient is quested? I.e. the tape could try to be smart enough to decompose only in case a user actually takes a derivative with respect to the parameters feeding into the `QubitStateVector `?

**Comment by cvjjm** [comment]
I see. But couldn't the decomposition be done in the jacobian method of the respective tapes in a way that works for each interface?

**Comment by josh146** [comment]
Yeah, that was my idea at the time. It ended up failing because if you call the gradient decompositions _inside_ the gradient logic, you can enter a case where classical processing occurs, which can't be tracked by the autodiff framework; so you end up with the incorrect gradients being returned.

E.g., if you have a decomposition that looks like

```
Gate1(x) -> [Gate2(x^2), Gate3(sin(x))]
```

--- that is, a quantum gate is decomposed down to quantum + classical components --- the parameter-shift rule would only give the quantum component, the classical component is lost.

I tried several workarounds, one being manually tracking the classical component of the Jacobian, and returning `class_jac @ quantum_jac`, but this ended up adding a lot of complexity and overhead 🤔 I also couldn't get it to work for all edge cases at the time, if I recall.

Moving the gradient-based decomposition _outside_ the interface, where the autodiff frameworks can continue to track classical processing, solves this, with the disadvantage being as we discussed above.

But this is definitely something we would love to support; being able to compute hybrid Jacobians without relying on the autodiff frameworks would solve this.
