### ISSUE TITLE
[BUG] Device jacobian is called without the user requesting a jacobian

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#2152]
### Expected behavior

In the sample program below the device jacobian should not be called as not derivative is calculated and the output `1.0
` should be printed. This was the behavior until 0.19.1.

### Actual behavior

The device jacobian is called, which can be an expensive operation, and here is made to raise an exception. This is the behavior from 0.20 onwards.

### Additional information

The sample code looks similar to #2146 but I think this issue is unrelated.

### Source code

```shell
import pennylane as qml
from pennylane.devices import DefaultQubit
from pennylane import numpy as np

class MyDev(DefaultQubit):
    @classmethod
    def capabilities(cls):
        capabilities = super().capabilities().copy()
        capabilities.update(
            provides_jacobian=True,
        )
        return capabilities

    def jacobian(self, operations_or_tape, observables=None, parameters=None):
        raise Exception("This exception signals that the device jacobian() was called")

@qml.qnode(MyDev(wires=2), diff_method='device')
def circuit(params):
    return qml.expval(qml.Hermitian(np.array([[1, 0], [0, 0]]), wires=0))

params = np.array([0.75916255, -2.16921113])

expval = circuit(params)
print(expval)
```

### Tracebacks

```shell
Traceback (most recent call last):
  File "pl_test5.py", line 23, in <module>
    expval = circuit(params)
  File "/.../pennylane/pennylane/qnode.py", line 561, in __call__
    res = qml.execute(
  File "/.../pennylane/pennylane/interfaces/batch/__init__.py", line 390, in execute
    res = _execute(
  File "/.../pennylane/pennylane/interfaces/batch/autograd.py", line 64, in execute
    return _execute(
  File "/.../autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "/.../pennylane/pennylane/interfaces/batch/autograd.py", line 108, in _execute
    res, jacs = execute_fn(tapes, **gradient_kwargs)
  File "/.../lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/.../pennylane/pennylane/_device.py", line 536, in execute_and_gradients
    jacs.append(gradient_method(circuit, **kwargs))
  File "pl_test5.py", line 15, in jacobian
    raise Exception("This exception signals that the device jacobian() was called")
Exception: This exception signals that the device jacobian() was called
```

### System information

```shell
Platform info:           Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.10
Python version:          3.8.8
Numpy version:           1.20.1
Scipy version:           1.6.1
Installed devices:
- default.gaussian (PennyLane-0.21.0.dev0)
- default.mixed (PennyLane-0.21.0.dev0)
- default.qubit (PennyLane-0.21.0.dev0)
- default.qubit.autograd (PennyLane-0.21.0.dev0)
- default.qubit.jax (PennyLane-0.21.0.dev0)
- default.qubit.tf (PennyLane-0.21.0.dev0)
- default.qubit.torch (PennyLane-0.21.0.dev0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by josh146** [comment]
Hi @cvjjm --- apologies, this is a breaking gradient logic change that was made to v0.20 due to our integration with `lightning.qubit`, that should have gone through a deprecation cycle.

In previous version of PennyLane, all calls to `jacobian` only occurred on the backwards pass, as you note. With the gradient logic improvements in v0.20, we now support two modes; `mode="backward"` (accumulate gradients on the backwards pass) and `mode="forward"` (accumulate gradients on the forward pass).

This can be toggled within the QNode:

```python
@qml.qnode(dev, mode="backward")
```

> **mode** (`str`) – Whether the gradients should be computed on the forward pass (forward) or the backward pass (backward). Only applies if the device is queried for the gradient; gradient transform functions available in `qml.gradients` are only supported on the backward pass.

The reason for supporting both is we noticed that some device jacobian methods rely on state caching, and are in fact more efficient if performed on the forward pass. As this is true for `lightning.qubit` and the adjoint method, we changed the default to `mode="forward"`.

Are there tweaks we can make to this behaviour to make it work better with your workflow?

Perhaps something we could do is have the device 'declare' which mode it prefers?

**Comment by cvjjm** [comment]
> Perhaps something we could do is have the device 'declare' which mode it prefers?
That sounds very good!

**Comment by cvjjm** [comment]
Actually, for non-passthrough devices it seems unlikely that "forward" could ever be advantageous over "backward". Maybe that could be used to decide on the default?

**Comment by cvjjm** [comment]
Actually also the docstring is a bit misleading imho:

> mode (str) – Whether the gradients should be computed on the forward pass (forward) or the backward pass (backward). **Only applies if the device is queried for the gradient**; gradient transform functions available in qml.gradients are only supported on the backward pass.

As the example above shows this also applies when the user is not querying the device for a gradient :-)

**Comment by josh146** [comment]
> Actually, for non-passthrough devices it seems unlikely that "forward" could ever be advantageous over "backward". Maybe that could be used to decide on the default?

For PennyLane lightning, I believe this is advantageous simply because we use the adjoint gradient method. So if we send a batch of tapes for execution, it requires less memory --- with only a slight computational overhead --- to extract `(result, gradient)` as each tape is being executed, as compared to caching each statevector for a later backwards pass.

But, you may be right --- the adjoint method is likely an outlier in this case (and, we are also exploring how we can reformulate it to return VJPs instead, which will probably make 'backward' more beneficial).

> As the example above shows this also applies when the user is not querying the device for a gradient :-)

Good catch 🤦‍♂️ I think we could tweak this as follows: we only compute the gradient on the forward pass *if*:

- `mode="forward"` _and_
- traced tensors are present as input tape arguments (indicating that tracing for backpropagation is occurring).

**Comment by josh146** [comment]
@cvjjm I've opened a new issue #2188 to track the two feature requests that came out of this issue, feel free to leave a comment there if there is anything I missed!
