### ISSUE TITLE
Avoid diagonalizing generators every time a parameter shift jacobian is calculated 

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#2220]
This is just a suggestion, feel free to ignore:

These lines of code are executed many times when constructing the recipe during parameter shift jacobian computation:

https://github.com/PennyLaneAI/pennylane/blob/ca0c079905974ddd3735177a306fad61ce7c9ded/pennylane/operation.py#L1212-L1218

The construction of the generator and its diagonalization are relatively expensive operations given the frequency with which these lines are executed, especially when the generator is larger than just a 2x2 matrix. Double construction of the generator can be avoided trivially by re-using `gen` in place of `self.generator()` in line 1217 the eigenvalues can probably be either cached in the Operator class or instance or Operations can at least be given the option to specify their generator eigenvalues directly to avoid matrix diagonalization.

**Comment by cvjjm** [comment]
This was again for a custom operation... I was not aware of `parameter_frequencies`. Seems like this pretty much implements already what I suggested above. Let me have a look to confirm this...

**Comment by josh146** [comment]
@cvjjm I had a chat to @dwierichs: it sounds like this issue has arisen because we are in the process of integrating general shift rules, but the process isn't complete yet!

At the end of the process it should work as follows, in order of precedence from highest to lowest:

1. If an operation defines `grad_recipe`, this is used by the parameter shift rule.

2. Otherwise, if `parameter_frequencies` are defined, this is used internally to compute, cache, and apply the general shift rule.

3. Otherwise, if `generator` is defined, the generator eigenvalues are used to compute and cache `parameter_frequencies`, and this is used internally to compute, cache, and apply the general shift rule.

4. Finally, if none of `grad_recipe`, `parameter_frequencies`, or `generator` are defined, the operation is decomposed recursively until we have operations where these are defined.

The issue is, we haven't yet finished the work that makes `grad_recipe` highest in precedence! Hence the behaviour you are currently seeing

**Comment by cvjjm** [comment]
Nice! Thanks for the explanation! In my case this lead to nearly double the execution time with `master` compared to `v0.21.0`, which is why I noticed.

It would be great if this could all be documented in the new guide on how to write custom Operations.

**Comment by dwierichs** [comment]
@cvjjm Besides documentation, i.e. the custom operation guide, has this issue been resolved by #2227?

**Comment by cvjjm** [comment]
Yes, this seems to be resolved. Thanks for the good work!
