### ISSUE TITLE
Hermitian observables and (avoiding) diagonalization of (large) matrices

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#2269]
### Feature details

This is half a question and half a feature / documentation request.

One issue with the `qml.Hermitian` observable is that (at least when running on `default.qubit`) its `.matrix` is diagonalized (via `.diagonalizing_gates`) even to compute return values such as `qml.expval(qml.Hermitiaion(...))` and  `qml.var(qml.Hermitiaion(...))`, which could be computed via a simple matrix vector (inner)products. This is already not ideal performance wise when the `qml.Hermitian` observable acts on few wires, but gets worse exponentially for large number of wires.

Looking into `DefaultQubit.expval()` I get the impression that for `qml.Hamiltonian` and `qml.SparseHamiltonian` this diagonalization is avoided.

So, am I right that wrapping a `qml.Hermitian` observable in a `qml.Hamiltonian` (as also discussed [here](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.Hamiltonian.html?highlight=hamiltonian#pennylane.Hamiltonian)) avoids the diagonalization?

- Maybe it would be worth explaining this to users?
- Maybe the same trick could be enabled to also speed up `var()`?
- Maybe this wrapping, which is counter intuitive and difficult to explain to users could be avoided altogether by calculating the diagonalizing gates of `qml.Hermitian` only when the user executes a `QNode` with a return type that requires diagonalization such as `qml.probs()` but not for `expval` or `var`?

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by josh146** [comment]
Hey @cvjjm!

> Looking into `DefaultQubit.expval()` I get the impression that for `qml.Hamiltonian` and `qml.SparseHamiltonian` this diagonalization is avoided.

Very good point - we should extend this behaviour to include `qml.Hermitian` as well.

This would also fix other issues, at least in `default.qubit` - I noticed today that, because `np.linalg.eigvalsh` does not preserve the order of eigenvalues wrt the computational basis, the eigenvalues of `qml.Hermitian(A, wires=[2, 0, 1])` (where the wires are in non-standard order) are incorrect, leading to incorrect expectation values.

> So, am I right that wrapping a `qml.Hermitian` observable in a `qml.Hamiltonian` (as also discussed [here](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.Hamiltonian.html?highlight=hamiltonian#pennylane.Hamiltonian)) avoids the diagonalization?

This is a very good question... I would need to double check. Let me get back to you on this one.

Another approach could be to do

```pycon
>>> H = qml.utils.decompose_hamiltonian(an_array, hide_identity=True)
```
and then `qml.expval(H)`. But this will probably not scale well as the size of the array increases, due to the line

https://github.com/PennyLaneAI/pennylane/blob/281e55f1d7f36901501535ddc2a903a3b146a463/pennylane/utils.py#L87

which looks like it might scale exponentially.

**Comment by josh146** [comment]
@cvjjm I can confirm that wrapping a `qml.Hermitian` observable in a Hamiltonian avoids the diagonalization.

For example,

```python
A = np.array([[1., 2.], [2., 3.]])

dev = qml.device("default.qubit", wires=1)

@qml.qnode(dev)
def circuit():
    qml.RX(0.5, wires=0)
    return qml.expval(1.0 * qml.Hermitian(A, wires=0))
```

since

```pycon
>>> 1.0 * qml.Hermitian(A, wires=0)
<Hamiltonian: terms=1, wires=[0]>
```

Internally, what will happen now is:

1. The dense array is converted into a sparse array: https://github.com/PennyLaneAI/pennylane/blob/1fdbcb56e0695668f4e2987550e5999e06fbf640/pennylane/devices/default_qubit.py#L517-L518

2. The inner product with the state is computed: https://github.com/PennyLaneAI/pennylane/blob/1fdbcb56e0695668f4e2987550e5999e06fbf640/pennylane/devices/default_qubit.py#L522-L526

**Comment by josh146** [comment]
I have a prototype hotfix here, but it is a bit ugly: https://github.com/PennyLaneAI/pennylane/pull/2270

**Comment by cvjjm** [comment]
I came up with this similarly ugly approach in a class derived from `DefaultQubit`
```
    def execute(self, circuit, **kwargs):
        if self.fake_hermitian:
            # loop over all observables from the
            # computational graph and monkey-patch away their
            # diagonalizing gates if it is of type Hermitian
            # and an expval or var
            def empty_list(_):
                return []

            observables = circuit.graph.observables if hasattr(circuit.graph, 'observables') else circuit.graph.nodes
            for observable in observables:
                if isinstance(observable, Hermitian) and observable.return_type in [ObservableReturnTypes.Expectation, ObservableReturnTypes.Variance]:
                    observable.diagonalizing_gates = empty_list.__get__(observable, Hermitian)

        return super().execute(circuit, **kwargs)

```
Be careful that if you do this then you need to change bot `expval` and `var` to also behave differently in this special case.

**Comment by josh146** [comment]
The best approach would be if we could tell `tape.diagonalizing_gates` to ignore a particular observable.

But this requires turning it into a method, which is a breaking change 🤔 

```pycon
>>> tape.diagonalizing_gates(ignore="Hermitian")
```

[The realization that we needed to pass more options to existing properties is part of the reason we have ported other operator properties to methods lately 🙂]

**Comment by cvjjm** [comment]
Agree, but `tape.diagonalizing_gates` is not part of the public API, isn't it? So breaking is not an issue here.

**Comment by cvjjm** [comment]
> Unfortunately though this pipeline seems to be blocked for more than one wire 🙁
> 
> https://github.com/PennyLaneAI/pennylane/blob/281e55f1d7f36901501535ddc2a903a3b146a463/pennylane/utils.py#L158-L163

But this could easily be made to work now that `qml.matrix()` exists.

**Comment by cvjjm** [comment]
Not with a sparse matrix but this is fine. It just is exponentially constly to compute expval, but diagonalization is much more costly than the dense matrix contraction (actually independently of the number of qubits)

**Comment by josh146** [comment]
> But this could easily be made to work now that qml.matrix() exists.

@cvjjm good point! I will look into integrating this

**Comment by cvjjm** [comment]
This is also related to #1344

**Comment by cvjjm** [comment]
I believe this was solved in https://github.com/PennyLaneAI/pennylane/pull/4866 Thanks!
