### ISSUE TITLE
[BUG] Extra gates with qml.cond

### ISSUE THREAD

**Issue by KetpuntoG** [PennyLaneAI/pennylane#2327]
### Expected behavior

If I run this code I would expect only the measurements to be painted.

```python

dev = qml.device("default.qubit", wires = 6)

@qml.qnode(dev)
def circuit():

    for ind, i in enumerate(range(3,6)):
        #qml.CNOT(wires = [ind, i])
        m = qml.measure(i)
        qml.cond(m == 1, qml.PauliX)(wires = ind)
            
    return qml.expval(qml.PauliZ(0)@qml.PauliZ(1)@qml.PauliZ(2))

circuit()
qml.draw_mpl(circuit)()

```

### Actual behavior

For some reason, a Z gate appears at the end of the circuit. 

### Additional information

If I change the observables to qml.PauliX the gate that appears is an X gate. Also, if I only work with 2 qubits, this bug does not appear.

### System information

```shell
pennylane 0.22
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by antalszava** [comment]
Hi @KetpuntoG, thank you so much for catching this! :tada: 

This will be an issue with how we iterate over the operations and measurements in the `defer_measurements` transform here:
https://github.com/PennyLaneAI/pennylane/blob/c379bb6e19f4b170f0c953e4322388a8335e0f3f/pennylane/transforms/defer_measurements.py#L93

`tape.queue` will contain annotated items too and what we'd like to do there is instead iterate over `tape.operations + tape.measurements`. In the example you post, `qml.PauliZ(2)` is included as a separate item in `tape.queue` due to annotation.
