### ISSUE TITLE
Automatically qml.broadcast single qubit gates when list of wires is passed

### ISSUE THREAD

**Issue by Qottmann** [PennyLaneAI/pennylane#2563]
### Feature details

Requesting a qiskit-style automatic broadcasting of single qubits when list of wires is passed to single qubit gates. This is useful when constructing Ansatz circuits by hand and we want to single qubits to act on multiple wires.  

To achieve this, the current behavior / usage is

```python
import pennylane as qml
dev = qml.device("default.qubit",wires=4)
wires = [0,1,2,3]
@qml.qnode(dev)
def circuit(x):
    for i in wires:
        qml.RX(x[i],wires=i)
    return qml.expval(qml.PauliZ(0))

print(qml.draw(circuit)([1,2,3,4]))
0: ──RX(1.00)─┤  <Z>
1: ──RX(2.00)─┤     
2: ──RX(3.00)─┤     
3: ──RX(4.00)─┤     
```
Alternatively we could do an in-line for loop which is already pretty close to the desired behavior:
```python
@qml.qnode(dev)
def circuit(x):
    [qml.RX(x[i],wires=i) for i in wires]
    return qml.expval(qml.PauliZ(0))

print(qml.draw(circuit)([1,2,3,4]))
0: ──RX(1.00)─┤  <Z>
1: ──RX(2.00)─┤     
2: ──RX(3.00)─┤     
3: ──RX(4.00)─┤     
```

I think broadcast is not something that many (new) users know of. What I am requesting would be achieving the above with the following code:
```python
def circuit(x):
    qml.RX(x,wires=[0,1,2,3])
    return qml.expval(qml.PauliZ(0))
```
So the single qubit gate RX automatically detects that it has been given a list instead of a single wire. This behavior is common for example in qiskit.

### Implementation

The more I think about implementation the more I am unsure whether it is feasible.

My idea was to modify the single qubit gate classes RX, RY, RZ, Hadamard,..etc. by performing a check whether the input for wires is sequential, and then pass qml.broadcast() of itself. Something like
```python
    if wires is not (isinstance(wires, int) or len(wires) == 1):
        assert len(phi) == len(wires)
        return [self.gate(phi[i],wires=i) for i in wires]
```
One of the most obvious problem with this is that it is recursive, i.e. it is calling itself. Another problem is that now the class would be returning something whereas in the individual case it would not.  

Another approach would be to do this on the tape level.

### How important would you say this feature is?

1: Not important. Would be nice to have.

### Additional information

The task can be divided into the following sub tasks:

1. Come up with sensible implementation solving the aforementioned problems OR a new approach that yields the same desired behavior.
2. Implement it in at least `qml.RX`, `qml.RY`, `qml.RZ`, `qml.Hadamard` 
3. Add tests in e.g. `/tests/test_broadcast_single_qubit_gates.py` covering the new functionalities.

**Comment by dwierichs** [comment]
I am not sure whether or where there was a discussion on this.

By now, we have parameter broadcasting of parametrized operations, so that:
a. `RX(scalar, single_wire)` is a single `RX` gate with a single rotation angle on a single wire
b. `RX(1d_tensor, single_wire)` is a single `RX` gate with broadcasted rotation angles on a single wire (corresponding to multiple tapes on QPUs, where each tape has one `RX` with a single angle).

The suggestion from this issue would add the case
c. `RX(1d_tensor, wire_list)` are multiple `RX` gates with a single rotation angle and a single wire each.

This yields the following potential confusions, from my point of view:
1. Users could know only about b. (parameter broadcasting) and assume that c. actually produces multiple tapes, where each tape only has one `RX` gate with a single rotation gate and wire.
2. Users could know only about c. (gate broadcasting via `qml.broadcast`) and assume that b. creates a sequence of multiple `RX` gates on the same wire.
3. Users could try to combine b. and c., passing `RX(2d_tensor, wire_list)`, with the expectation of broadcasting `RX` across the wires and giving each gate a parameter-broadcasted input. (This scenario is a bit far fetched probably)

**Comment by albi3ro** [comment]
I think we ended up deciding that wire broadcasting would cause a lot of internal problems while it is a very easy thing for users to control manually.

Especially since they can just do `[qml.PauliX(w) for w in wires]`.

**Comment by josh146** [comment]
Yes, I think @Qottmann and I chatted about this at some point, and came back to what you mention @albi3ro: this is something that could be coded up by a user via a `for` loop or list comprehension, so then it becomes a question of:

- is it worth adding complexity to the codebase for something that can be coded up easily by users
- this could add ambiguity (like @dwierichs mentions)

**Comment by dwierichs** [comment]
Thanks for the update, @albi3ro @josh146 !
Do we want to close this issue, then? :thinking:

**Comment by Qottmann** [comment]
Yes indeed! Sorry I forgot this was still open, closing now 👍
