### ISSUE TITLE
Regression in qml.gradients.param_shift_hessian() [BUG]

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#2816]
### Expected behavior

The expected behavior is that the hessian is correctly computed and this is what pennylane == 0.23.0 does.

### Actual behavior

From pennylane 0.24.0 onwards (the problem is still present in the current master) something goes wrong when `param_shift_hessian()` calls `_process_argnum()` https://github.com/PennyLaneAI/pennylane/blob/6019194744d8357e382e5019265ebc70db37d87f/pennylane/gradients/parameter_shift_hessian.py#L463
after being called with `argnum=None` 
The latter function 
https://github.com/PennyLaneAI/pennylane/blob/6019194744d8357e382e5019265ebc70db37d87f/pennylane/gradients/parameter_shift_hessian.py#L38-L63
sets `argnum = tape.trainable_params` and then surprisingly raises the exception after `qml.math.max(argnum) >= tape.num_params` evaluates to true. 

I have not yet managed to cook up a minimal example, but it seems to only happen for some QNodes and work for others. 

Regardless, I do not understand how `qml.math.max(tape.trainable_params)` can ever be larger than `tape.num_params`, so clearly there is some bug in PennyLane.

Any help, thoughts or suggestions are welcome. I will try to provide more information.

### System information

```shell
Name: PennyLane
Version: 0.25.0.dev0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: /home/cvjjm/src/covqcstack/qcware/pennylane
Requires: numpy, scipy, networkx, retworkx, autograd, toml, appdirs, semantic-version, autoray, cachetools, pennylane-lightning
Required-by: pytket-pennylane, PennyLane-Qchem, PennyLane-Lightning, covvqetools

Platform info:           Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.10
Python version:          3.8.8
Numpy version:           1.20.1
Scipy version:           1.8.0
Installed devices:
- default.gaussian (PennyLane-0.25.0.dev0)
- default.mixed (PennyLane-0.25.0.dev0)
- default.qubit (PennyLane-0.25.0.dev0)
- default.qubit.autograd (PennyLane-0.25.0.dev0)
- default.qubit.jax (PennyLane-0.25.0.dev0)
- default.qubit.tf (PennyLane-0.25.0.dev0)
- default.qubit.torch (PennyLane-0.25.0.dev0)
- pytket.pytketdevice (pytket-pennylane-0.1.0)
- lightning.qubit (PennyLane-Lightning-0.24.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by antalszava** [comment]
Hi @cvjjm, thank you for finding this and for the detailed description. :pray: It's super helpful, we'll look into this one!

**Comment by rmoyard** [comment]
I've started working on it, I removed the problem with `num_params` but the param shift hessian was not designed for this case and needs to be updated.

**Comment by cvjjm** [comment]
It would be really, really great if this could be fixed in time for the 0.25.0 release, since this would be the first version since 0.18.0 that would then be bug free for our purposes :-). Since @dwierichs did #2538 , maybe he can/wants to chime in as well?

**Comment by dwierichs** [comment]
I think because the API of `argnum` for `param_shift_hessian` is not very consistent with the separation of tapes and QNodes (`argnum` _always_ refers to tape arguments and never to QNode arguments, unlike gradient functions), there are multiple ways forward here. It mostly depends on what we want to be able to do:

1. We could ignore parameters that are not recognized by the tape as trainable altogether. That means, that users will not be able to compute the Hessian w.r.t a parameter that is not trainable according to the tape (which I personally find kind of reasonable).
Note that changing which parameters are considered trainable by the tape is really easy, as in `tape.trainable_params = {...}`.
2. We could allow for differentiation w.r.t to untrainable (as per tape recognition) parameters. This would require to restructure the Boolean mask to have "full" dimension, i.e. to be as large as the number of trainable+untrainable parameters together.
I see multiple issues with this:
a) Users always have to consider untrainable parameters when providing `argnum`. That is, for the example by @cvjjm above, `argnum=[True, True]` would be invalid, but `[False, True, True]` would be allowed. While the benefit here would be that we even can do `argnum=[True, True, True]`, i.e. computing the Hessian also w.r.t the first, untrainable parameter, I personally find this confusing. For circuits with large numbers of untrainable parameters, this also might become annoying.
b) The returned Hessian would have to have the same dimension as `argnum`, i.e. the example above would always return a `(3, 3)`-shaped Hessian. That's also not very intuitive to me personally. In particular it does not match the length of gradients/last dim of Jacobians of the same QNode, which might be confusing.

I therefore suggest to stick to `argnum` - and the output Hessian - to have dimension `tape.num_params` (so only ever consider trainable parameters, as reported per tape).
The only bug to be fixed is then to change 
```py
argnum = tape.trainable_params
```
to
```py
argnum = list(range(tape.num_params))
```
With this change, the above code example works :)
```pycon
>>> hess(params)
[[-9.75170327e-01  1.12985306e-18]
 [ 1.12985306e-18  5.55111512e-17]]
```

**Comment by cvjjm** [comment]
The path 1 and the proposed fix of @dwierichs look perfectly fine for me. 

In the future one might consider allowing for argnum to be "total number of parameters" large and then compute the full hessian, but I agree that the default for argnum=None should be as described by @dwierichs above.
