### ISSUE TITLE
[BUG] Kernel Crash with circuit_cut

### ISSUE THREAD

**Issue by PatrickHuembeli** [PennyLaneAI/pennylane#2848]
Hi everyone,

I am trying to run the QAOA example code with the `cut _circuit` function:

````
import pennylane as qml
from pennylane import qaoa
from pennylane import numpy as np
from matplotlib import pyplot as plt
import networkx as nx

edges = [(0, 1), (1, 2), (2, 0), (2, 3)]
graph = nx.Graph(edges)
cost_h, mixer_h = qaoa.min_vertex_cover(graph, constrained=False)

def qaoa_layer(gamma, alpha):
    qaoa.cost_layer(gamma, cost_h)
    qaoa.mixer_layer(alpha, mixer_h)

wires = range(4)
depth = 2

dev = qml.device("default.qubit", wires=wires)

@qml.cut_circuit(auto_cutter=True)
@qml.qnode(dev)
def circuit(params, **kwargs):
    for w in wires:
        qml.Hadamard(wires=w)
    qml.layer(qaoa_layer, depth, params[0], params[1])
    return qml.expval(cost_h)

optimizer = qml.GradientDescentOptimizer()
steps = 70
params = np.array([[0.5, 0.5], [0.5, 0.5]], requires_grad=True)

for i in range(steps):
    params = optimizer.step(circuit, params)
````

And the kernel crashes at the last line with the Warning: `UserWarning: The numer of partition attempts seems high (36).
  warnings.warn(f"The numer of partition attempts seems high ({len(ks)}).")
[2]    65374 illegal hardware instruction`

The code works if I remove the `cut_circuit` wrapper.
Does anyone know what the issue is here? Does the cutter have problems with the qaoa layers?
I also tried different graphs. For example `edges = [(0, 1), (1, 2), (2, 3)]`. And QAOA with depth p=1. Same outcome.
In case this helps. I am running this on an Apple Silicon M1, pennylane v0.24 

### System information

```shell
Name: PennyLane
Version: 0.24.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /Users/patrickhuembeli/anaconda3/envs/QCJAX2/lib/python3.9/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, retworkx, scipy, semantic-version, toml
Required-by: PennyLane-Lightning

Platform info:           macOS-12.4-x86_64-i386-64bit
Python version:          3.9.13
Numpy version:           1.22.3
Scipy version:           1.7.3
Installed devices:
- lightning.qubit (PennyLane-Lightning-0.24.0)
- default.gaussian (PennyLane-0.24.0)
- default.mixed (PennyLane-0.24.0)
- default.qubit (PennyLane-0.24.0)
- default.qubit.autograd (PennyLane-0.24.0)
- default.qubit.jax (PennyLane-0.24.0)
- default.qubit.tf (PennyLane-0.24.0)
- default.qubit.torch (PennyLane-0.24.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by antalszava** [comment]
Hi @PatrickHuembeli, thank you, we'll look into this and get back to you! :)

**Comment by anthayes92** [comment]
Hi @PatrickHuembeli, 

Thanks for trying out the circuit cutting functionality! 

Circuit cutting for QAOA is a highly nontrivial problem, there are a couple of key aspects to consider. The first is that the circuit built by using `qaoa.cost_layer` and `qaoa.mixer_layer` will consist of [`ApproxTimeEvolution`](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.ApproxTimeEvolution.html#pennylane.ApproxTimeEvolution) operations, in order to perform circuit cutting these should be decomposed to [`PauliRot` ](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.PauliRot.html) operations (as well as phase shift operations ). This is a limitation of the current `cut_circuit` decorator since the decomposition can't be specified at this level. However an alternative workflow is available at the [`tape`](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.tape.QuantumTape.html) level: 

```python
import pennylane as qml
from pennylane import qaoa
from pennylane import numpy as np
from matplotlib import pyplot as plt
import networkx as nx

edges = [(0, 1), (1, 2), (2, 0), (2, 3)]
graph = nx.Graph(edges)
cost_h, mixer_h = qaoa.min_vertex_cover(graph, constrained=False)

def qaoa_layer(gamma, alpha):
    qaoa.cost_layer(gamma, cost_h)
    qaoa.mixer_layer(alpha, mixer_h)

wires = range(4)
depth = 2

dev = qml.device("default.qubit", wires=wires)

@qml.qnode(dev)
def circuit(params, **kwargs):
    for w in wires:
        qml.Hadamard(wires=w)
    qml.layer(qaoa_layer, depth, params[0], params[1])
    return qml.expval(cost_h)

params = np.array([[0.5, 0.5], [0.5, 0.5]], requires_grad=True)
circuit(params)

tape = circuit.qtape
etape = tape.expand(depth=1)

graph = qml.transforms.qcut.tape_to_graph(etape)
cut_edges = qml.transforms.qcut.kahypar_cut(
        graph=graph,
        num_fragments=2,
    )
cut_graph = qml.transforms.qcut.place_wire_cuts(graph=graph, cut_edges=cut_edges)
cut_tape = qml.transforms.qcut.graph_to_tape(cut_graph)
```

and the manual cutting workflow outlined [here](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.cut_circuit.html#details) can be performed.

Note that the resulting tape now has fixed parameters. This is the second non trivial aspect of circuit cutting with QAOA, the parameters need to be updated at each step of the optimisation, using the above method means a new tape is required for each step. We anticipate a paper to be released on arXiv early next week which details how this can be achieved. 

These aspects of circuit cutting for QAOA require extensions to the `cut_circuit` decorator, we encourage any contributions to this. This doesn't seem to be a bug with the current decorator, but please let us know if you think we have missed something here!

**Comment by AlbertMitjans** [comment]
Closing this issue.
