### ISSUE TITLE
Move code from `qml.utils.sparse_hamiltonian` to `Hamiltonian.sparse_matrix`

### ISSUE THREAD

**Issue by albi3ro** [PennyLaneAI/pennylane#3236]
Right now, we have a function [`qml.utils.sparse_hamiltonian`](https://github.com/PennyLaneAI/pennylane/blob/cf195af015a7ee9098c74e42da90d9f709dfe1c5/pennylane/utils.py#L111) responsible for constructing a SciPy sparse matrix from a Hamiltonian.

`Operator`'s like [`Hamiltonian`](https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/ops/qubit/hamiltonian.py)  have a [`sparse_matrix`](https://github.com/PennyLaneAI/pennylane/blob/cf195af015a7ee9098c74e42da90d9f709dfe1c5/pennylane/operation.py#L503)  method. This is currently undefined for `Hamiltonian`, even though we already have the code for constructing the sparse matrix for a Hamiltonian.

A PR completing this issue would:
* Move the code from `qml.utils.sparse_hamiltonian` to `Hamiltonian.sparse_matrix`
* Move relevant tests from `tests/test_utils.py` to `tests/ops/qubit/test_hamiltonian.py`.
* Add a deprecation warning using `warnings.warn` to `qml.utils.sparse_hamiltonian`
* Add a test catching the deprecation warning to `tests/test_utils.py`
* Add two changelog entries to `doc/releases/changelog-dev.md` : one in "Improvements" and one in "Deprecations"

**Comment by 12mB7693** [comment]
@albi3ro Hi, I would like to work on this issue. If possible, can you assign it to me?

**Comment by 12mB7693** [comment]
@albi3ro Thank you! Unfortunately, I am struggling a bit to create a "Work in Progress" pull request. I created a local branch, but I am not sure, how to push this to the pennylane repo in order to create a pull request. Maybe i missed something there, but I also could not find further details in the contribution guide.

**Comment by CatalinaAlbornoz** [comment]
Hi @12mB7693, I can help with that! I made a guide that can help with this part of the contribution process. My guess is that you haven't made any commits yet so this is why you're having trouble at the moment. Please let me know if you have any further questions!

[Guide - Contributing to PennyLane.pdf](https://github.com/PennyLaneAI/pennylane/files/10108861/Guide.-.Contributing.to.PennyLane.pdf)

**Comment by 12mB7693** [comment]
Hi @CatalinaAlbornoz , thank you for the guide! I tried to follow the steps, however, in the step where you have to click on "New branch", I do not have this option (so basically I only see the button "All branches" and there is no "New branch" button next to it). It would be indeed my first commit, so maybe I am missing something which you only have to do once when you are a new contributor.
![Screenshot from 2022-12-04 13-54-47](https://user-images.githubusercontent.com/55717637/205491675-947bbe3f-fac7-4d4d-9470-8b07ceddca00.png)

**Comment by CatalinaAlbornoz** [comment]
Hi @12mB7693 ,

You're totally right. It's not because it's your first commit, it's because you don't have write access to this repository (which is the way it should be). So you need to follow one additional step and it's creating a fork for the repository. This basically creates your own copy of the repository.

<img width="488" alt="image" src="https://user-images.githubusercontent.com/25390652/206559719-05dae61b-ae74-483b-aa91-58e29dd8712f.png">
Click on "+ Create a new fork" and then on the green button "Create fork".
<img width="765" alt="image" src="https://user-images.githubusercontent.com/25390652/206560106-0073c192-3618-4d05-8587-481f48ab5bbb.png">

You will now be working in your own version of PennyLane (the url will be something like https://github.com/12mB7693/pennylane) and you can create a branch there.

When you're ready to make your pull request don't make it your own repository. Instead you can go to https://github.com/pennylaneai/pennylane and you will see a suggestion to make a pull request there.
<img width="915" alt="image" src="https://user-images.githubusercontent.com/25390652/206560950-2d1542db-d13f-4415-a46d-ea8e469ed090.png">

If you look at the details when creating the Pull Request you will see that I'm merging the branch "patch-1" from my own version of PennyLane (the one that has my username) into the "master" branch of the official version of PennyLane (PennyLaneAI/pennylane).
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/25390652/206561114-cff70653-bcc5-4eb9-854e-1dbbde5e2be7.png">

I hope this is helpful for you and please let me know if you have any trouble!

**Comment by 12mB7693** [comment]
Thank you for the explanation, I created a Work in Progress PR (https://github.com/PennyLaneAI/pennylane/pull/3585). The automatic tests failed, but I assume that this is okay for this kind of PR?

**Comment by albi3ro** [comment]
PR merged.
