### ISSUE TITLE
[BUG] Confusing organization of tests for features related to `qinfo`

### ISSUE THREAD

**Issue by astralcai** [PennyLaneAI/pennylane#3580]
### Expected behavior

1. Each test file should only test one feature
2. Tests for `qnode` transforms should be placed in the `tests/qinfo` directory, and tests for measurement processes should be placed in the `tests/measurements` directory

### Actual behavior

1. Some test files are crowded with tests for multiple features, which makes it hard to find tests for certain features, for example, `tests/math/test_entropies_math.py` contains tests for `purity`, `vn_entropy`, `mutual_information` and `relative_entropy`, all in one file.
2. Some tests are placed in the wrong file, for example, `tests/measurements/test_mutual_info.py` should only contain tests for the mutual info measurement, but in fact, the `TestIntegration` class contains test cases such as `test_qnode_state` that is in fact testing the `qnode` transform.

### System information

```shell
N/A
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by Jaybsoni** [comment]
Hi @astralcai, 

Thanks for brining this up! This part of the code base could definitely use some clean up. Just to clarify, there wasn't anything actually breaking because of this, correct? We will for sure address this, but I just want to make sure it gets classified correctly. It seems that the `chore` label might be a better fit in this case. Let me know what you think! 

Thanks,

**Comment by astralcai** [comment]
Hi @Jaybsoni 

You are right, this doesn't break anything, so technically not a bug.

**Comment by astralcai** [comment]
`qinfo` does not exist anymore
