### ISSUE TITLE
[Bug] Inconsistent ordering in datasets for lists of parameters

### ISSUE THREAD

**Issue by Qottmann** [PennyLaneAI/pennylane#3855]
The ordering of lists of datasets when passed lists of parameters is of no canonical ordering, but appears to be random:

```python
bondlengths = ['0.5', '0.54', '0.58', '0.62']
data = qml.data.load("qchem", molname="H2", basis="STO-3G", bondlength=bondlengths)
print(data)
```
would expect output:
```pycon
[<Dataset = description: qchem/H2/STO-3G/0.5, attributes: ['molecule', 'hamiltonian', ...]>, 
<Dataset = description: qchem/H2/STO-3G/0.54, attributes: ['molecule', 'hamiltonian', ...]>, 
<Dataset = description: qchem/H2/STO-3G/0.58, attributes: ['molecule', 'hamiltonian', ...]>, 
<Dataset = description: qchem/H2/STO-3G/0.62, attributes: ['molecule', 'hamiltonian', ...]>]
```
but actually obtain:
```pycon
[<Dataset = description: qchem/H2/STO-3G/0.54, attributes: ['molecule', 'hamiltonian', ...]>, 
<Dataset = description: qchem/H2/STO-3G/0.5, attributes: ['molecule', 'hamiltonian', ...]>, 
<Dataset = description: qchem/H2/STO-3G/0.58, attributes: ['molecule', 'hamiltonian', ...]>, 
<Dataset = description: qchem/H2/STO-3G/0.62, attributes: ['molecule', 'hamiltonian', ...]>]
```

**Comment by timmysilv** [comment]
thanks for reporting this! the attribute ordering (per-parameter) gets randomized in [this line](https://github.com/PennyLaneAI/pennylane/blob/6daabc6cd265f5112e426bedcb57f4197b7fbb7c/pennylane/data/data_manager.py#L200) because it uses sets to remove any attributes the user provided that aren't actually available. I agree that the random ordering is unexpected behaviour, and should probably be fixed.

I had originally used sets here to ensure that we don't request any files that don't exist in S3, but I eventually added more pre-validation after writing that line of code! The set intersection is not really needed here, so I'll remove it.
