### ISSUE TITLE
Support qutrit state preparations

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/pennylane#4122]
### Feature details

PennyLane has growing support for qutrit-based calculations, with the addition of a [`default.qutrit`](https://docs.pennylane.ai/en/stable/code/api/pennylane.devices.default_qutrit.html#module-pennylane.devices.default_qutrit) device and some [qutrit gates](https://docs.pennylane.ai/en/stable/introduction/operations.html#qutrit-operators). One missing element is _state preparation_. We would like to add `QutritBasisState` (analogous to [`BasisState`](https://docs.pennylane.ai/en/stable/code/api/pennylane.BasisState.html)), allowing users to more easily specify the input state to qutrit-based circuits.

### Implementation

`QutritBasisState` should accept:
- `n` (array/tensor): the qutrit basis state, e.g., `[0, 2,  1, 2]` for a 4-qutrit system
- `wires`

The decomposition can be provided using [`TShift`](https://docs.pennylane.ai/en/stable/code/api/pennylane.TShift.html).

This addition should live in a `state_preparation.py` file within [pennylane.ops.qutrit](https://github.com/PennyLaneAI/pennylane/tree/master/pennylane/ops/qutrit) and include documentation, examples, and tests.

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by manulpatel** [comment]
Hello @trbromley! I would be happy to implement support for qutrit state prep. Could you please allow me to work and assign?

**Comment by khnikhil** [comment]
hi @trbromley! I just submitted a PR implementing a `QutritBasisState` class. I mark it as [WIP] because I haven't yet implemented the unit tests (though the documentation should be good!), but from testing it informally in a Jupyter notebook, it appears to be working nicely (see below screenshot).

I put more information in the PR (#4184), but if you have any feedback at this stage (or a confirmation that I went in the right direction), it would be much appreciated :) 

Also, please let me know if there's anything else I would need to implement!

<img width="514" alt="241664987-fb5864d2-366d-4f8e-82a7-f8ed370a38fc" src="https://github.com/PennyLaneAI/pennylane/assets/74874354/9750c1f9-fd64-4536-8fa2-180c3162b484">

**Comment by trbromley** [comment]
Thanks @khnikhil and @EmilianoG-byte! We'll take a look at each of your pull requests and give feedback asap.

Please note that we can only assign the bounty to one pull request, with the one that is merged first as the winner.

**Comment by khnikhil** [comment]
hi @EmilianoG-byte, 

should we split the bounty, since I submitted the original PR with `QutritBasisState` and `QutritBasisStatePrepatation` and you added some additional unit tests? @trbromley not sure what the typical procedure/etiquette is when two people submit PRs with quite similar code. fun working on this together :)

**Comment by trbromley** [comment]
@khnikhil, if you and @EmilianoG-byte are happy to work together on a single PR and split the bounty equally, that works for us! That's also [mentioned as an option](https://unitaryhack.dev/project-guide/#%F0%9F%9B%A0%EF%B8%8F-during-the-hack-%F0%9F%9B%A0%EF%B8%8F) on the UnitaryHack site :+1:

**Comment by EmilianoG-byte** [comment]
Hello! I want to apologise because I did not see @khnikhil had already submitted a PR. I actually coded  the main part (including the `default.qutrit` which I see is not in khnikhil's code) yesterday night. Since this is (almost) impossible to verify as I did not push until today, I guess the most Solomonic solution is to split the bounty. Sounds reasonable to me :)

Should then continue on my PR since I have passed already all the pipeline tests?

**Comment by lillian542** [comment]
@EmilianoG-byte @khnikhil Left a few comments on the PR #4185, thanks for working on this!

**Comment by khnikhil** [comment]
@EmilianoG-byte if you wrote your code without using mine then you should get the whole bounty! I'll close my PR. I just wanted to check bc of the timing :)

**Comment by EmilianoG-byte** [comment]
@khnikhil, I still think I should have checked you worked on it before though. Once again, I am sorry about that. I have added your name to the log of contributors, and I am more than happy to share the bounty with you. Also, there are still 1/2 comments left from @lillian542 review in case you have time to work on them :)
