### ISSUE TITLE
[BUG] `sum` not working with hardware Hamiltonians (transmons and rydberg)

### ISSUE THREAD

**Issue by BorjaRequena** [PennyLaneAI/pennylane#4310]
### Expected behavior

Working with hardware Hamiltonians, we add them together with similar syntax to `H = H_interaction + H_drive`. Often, we repeatedly add terms manually, e.g., `H_drive += qml.pulse.transmon_drive(amplitude, phase, freq, wires)`.

I would expect to be able to use `sum()` on a list of terms, such as:
`H_drive = sum([qml.pulse.transmon_drive(amplitude, phase, freq, q) for q in wires])`
Similar to how we can add other operators in PennyLane `sum([qml.PauliX(i) for i in range(wires)])`.

### Actual behavior

We can't do it.

### Additional information

I have tested this with a few `HardwareHamiltonian` instances using `qml.pulse.transmon_interaction`, `qml.pulse.transmon_drive`, `qml.pulse.rydberg_interaction` and `qml.pulse.rydberg_drive`.

We can manipulate all of them with stuff such as:
```python
H = qml.pulse.transmon_interaction(qubit_freqs, connection, couplings, wires)
for q in wires:
    H += qml.pulse.transmon_drive(amplitude, phase, freq, q)
```
Or even:
```python
H_int = qml.pulse.transmon_interaction(qubit_freqs, connection, couplings, wires)
drive_terms = [qml.pulse.transmon_drive(amplitude, phase, freq, q) for q in range(2)]
H_drive = drive_terms[0] + drive_terms[1]
H = H_int + H_drive
```

But we wouldn't be able to use `sum()` on any iterable containing `HardwareHamiltonian`s. I also tried changing the input types, e.g., setting `amplitude`, `phase`, and `freq` to be all callables, floats, or ints, or a combination of those.

### Source code

```shell
import pennylane as qml
sum([qml.pulse.transmon_drive(0., 0., 0., q) for q in range(2)])
```

### Tracebacks

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 2
      1 import pennylane as qml
----> 2 sum([qml.pulse.transmon_drive(0., 0., 0., q) for q in range(2)])

TypeError: unsupported operand type(s) for +: 'int' and 'HardwareHamiltonian'
```

### System information

```shell
Latest master

Name: PennyLane
Version: 0.32.0.dev0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /home/borja.requena/.conda/envs/pl_dev/lib/python3.10/site-packages
Editable project location: /home/borja.requena/GitHub/pennylane
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml
Required-by: PennyLane-Lightning

Platform info:           Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python version:          3.10.11
Numpy version:           1.23.5
Scipy version:           1.10.0
Installed devices:
- default.gaussian (PennyLane-0.32.0.dev0)
- default.mixed (PennyLane-0.32.0.dev0)
- default.qubit (PennyLane-0.32.0.dev0)
- default.qubit.autograd (PennyLane-0.32.0.dev0)
- default.qubit.jax (PennyLane-0.32.0.dev0)
- default.qubit.tf (PennyLane-0.32.0.dev0)
- default.qubit.torch (PennyLane-0.32.0.dev0)
- default.qutrit (PennyLane-0.32.0.dev0)
- null.qubit (PennyLane-0.32.0.dev0)
- lightning.qubit (PennyLane-Lightning-0.31.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by dwierichs** [comment]
This bug is due to the addition of `HardwareHamiltonian` and `int` not being defined. `sum` initializes the output to the integer `0` and subsequently adds the elements of the iterable, so that this bug occurs.
In my opinion we have the following options:

1.  We take the current behaviour to be intended and require users to manually sum terms, or to provide a `start` value as in
```python
hamiltonians = [...]
H = sum(hamiltonians[1:], start=hamiltonians[0])
```
2. We support addition between "empty" hardware Hamiltonians (`HardwareHamiltonian([], [])`) and other instances by ignoring the empty instance. This would allow users to do
```python
H = sum(hamiltonians, start=qml.pulse.HardwareHamiltonian([], []))
```
Note, however, that this basically is as cumbersome/convenient as the first option, while requiring a modification of the source code.
3. We implement addition between `HardwareHamiltonian` and `int` (and `float`) by adding a constant term to the Hamiltonian. Optionally, we could skip this added term if the number that is being added is close to zero. Note, however, that this skipping step may break JIT-compatibility.
4. We only implement addition with the integer `0` as a special case. Note however, that this would fix this very specific use case in a rather arbitrary place of the codebase.
5. We make `qml.sum` support `HardwareHamiltonian` and defer users to use `qml.sum` over `sum`.


What do you think, @Qottmann , @lillian542 , @trbromley ? :) What other options are there?

**Comment by dwierichs** [comment]
I agree with @Qottmann on this and would go for the third option above, without adding the special treatment of 0. This would, however, add a mild overhead unless users create their sum of `HardwareHamiltonians` using the syntax shown in point 1 above, or by using the `+=` syntax shown by @BorjaRequena.
@trbromley what is your opinion on this one? :)

**Comment by trbromley** [comment]
Option 3 makes the most sense to me. @dwierichs what is the overhead that would be added?

**Comment by dwierichs** [comment]
For a minimal Hamiltonian from the example above, computing `qml.matrix(H)` takes 1.1 µs instead of 900ns.
Executing a simple QNode took 333ms instead of 360ms.

These are very small examples, so that the overhead kicks in the most and it should be less relevant for bigger examples.
Still, it's not nothing.
