### ISSUE TITLE
[BUG] Mid Circuit measurements dont execute

### ISSUE THREAD

**Issue by CLEconomides** [PennyLaneAI/pennylane#4360]
### Expected behavior

Hello, I already posted on the Xanadu Forum ( https://discuss.pennylane.ai/t/mid-circuit-measurement-in-pennylane/3187 ) and was directed to also ask here as this might be a bug.
I should clarify that there is no error in the code but rather that it doesnt seem to do what i would expect it to. This could also be absolutely due to me but as said after asking on the Xanadu Forum i was advised to asked here.

I am trying to measure a qubit (and to also save that measurement) mid circuit and then continue operating on the rest of the register of qubits, or at least here to get the state of the qubit right after measurement. As an example here is a circuit that creates a bell state of (00 + 11)/sqrt(2):

```python
dev = qml.device(‘default.qubit’, wires=2)
@qml.qnode(device=dev)
def func():
    qml.Hadamard(0)
    qml.CNOT(wires=[0,1])
    qml.measure(wires=0)
    return qml.density_matrix(wires=1)
```

From the documentation i understand qml.measure(0) measures wire 0. But the qml.density_matrix, qml.state and qml.probs  give me after the measurement a 50% percent for the qubit 1 to be in state 0 or 1. But I know that based on what was measured on qubit 0 we know what qubit 1 is, since they are entangled.

I also added other times a conditional operation on the measurement. 
```python
measurement = qml.measure(0)
qml.cond(measurement, qml.Identity)(1) 
```
and still, although this operation is designed with the identity to not change the state, the state is still in its superposition of 00 and 11 although it was already measured.

I could understand that probs or density matrix would still give me maybe averaged over many shots and not only from one shot, but atleast the qml.state i would expect to return the  quantum state as it is after the measurement

### Actual behavior

What it actual does is what I referenced to already. It doesnt seem to apply the mid circuit measurement on qubit 0. It also doesnt show the measurement when i draw the circuit, although the conditional operation qml.cond() is shown.
0: ──H─╭●─╭●─┤       
1: ────╰X─╰I─┤  State

### System information

```shell
Name: PennyLane
Version: 0.31.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: c:\users\constantin\pycharmprojects\masterarbeit\venv\lib\site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml
Required-by: PennyLane-Lightning

Platform info:           Windows-10-10.0.19045-SP0
Python version:          3.9.13
Numpy version:           1.23.5
Scipy version:           1.10.0
Installed devices:
- default.gaussian (PennyLane-0.31.0)
- default.mixed (PennyLane-0.31.0)
- default.qubit (PennyLane-0.31.0)
- default.qubit.autograd (PennyLane-0.31.0)
- default.qubit.jax (PennyLane-0.31.0)
- default.qubit.tf (PennyLane-0.31.0)
- default.qubit.torch (PennyLane-0.31.0)
- default.qutrit (PennyLane-0.31.0)
- null.qubit (PennyLane-0.31.0)
- lightning.qubit (PennyLane-Lightning-0.31.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by trbromley** [comment]
Hi @CLEconomides! Thanks for raising this issue. It is also a good time because we have some big improvements planned for mid-circuit measurements that will be available in the 0.32 release towards the end of August.

So if we run the following circuit, we get:
```python
dev = qml.device(‘default.qubit’, wires=2)
@qml.qnode(device=dev)
def func():
    qml.Hadamard(0)
    qml.CNOT(wires=[0,1])
    qml.measure(wires=0)
    return qml.density_matrix(wires=1)
```
```pycon
>>> func()
tensor([[0.5+0.j, 0. +0.j],
        [0. +0.j, 0.5+0.j]], requires_grad=True)
```
That is, we observe a fully mixed-state on wire `1`. Although perhaps surprising at first sight, I believe this is correct:
- Suppose you measure wire `0` and observe $|0\rangle$. We know that wire `1` is also in the state $|0\rangle$ (since we have prepared the Bell state $|\Phi^{+}\rangle$ before measurement).
- Similarly, if you measure wire `0` and observe $|1\rangle$, we know that wire `1` is also in the state $|1\rangle$.
- However, on average you will observe wire `0` to be 50% of the time in state $|0\rangle$ and the other 50% of the time in state $|1\rangle$.
- Hence, _without any postselection on the measurement value on wire `0`_, the state of wire `1` should be $\frac{1}{2}|0\rangle\langle 0| + \frac{1}{2}|1\rangle\langle 1| = \mathbb{I} / 2$, which is the state we observe above.

What is missing in PennyLane is the ability to postselect on a mid-circuit measurement value. For example, we could have the following:
```python
dev = qml.device(‘default.qubit’, wires=2)
@qml.qnode(device=dev)
def func():
    qml.Hadamard(0)
    qml.CNOT(wires=[0,1])
    qml.measure(wires=0, postselect=0)  # See here!
    return qml.density_matrix(wires=1)
```
```pycon
>>> func()
tensor([[1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]], requires_grad=True)
```
Hence, we will know that we have measured $|0\rangle$ on both of the wires. As mentioned above, this is not yet available but is being explored for the next PennyLane release.

To also mention some of your other points:
- If you return `qml.state()` for the above circuit, you will currently get `tensor([0.70710678+0.j, 0.        +0.j, 0.        +0.j, 0.70710678+0.j], requires_grad=True)`, which is the state of both of the qubits before any measurement has taken place. This is a bug / edge case where the expectation is probably that `qml.state()` refers to just the state of wire `1`. We'll be fixing this!
- Finally, we'll also be adding improved drawing support for mid circuit measurements, so diagrams created from `qml.draw()` and `qml.draw_mpl()` should be much more intuitive with mid-circuit measurements.

**Comment by CLEconomides** [comment]
Hi, thank you for your quick response!

Thank you also for the explanations, they bring in much clarification. I would still have some questions especially since i cant wait until August for my project and would like to continue using pennylane rather than other packages.

In my case i dont truly need a postselection either. In my algorithm, that i havent talked about here, i only need to measure one qubit of the registe, during the circuit, in order collapse the rest of the register into the entangled state of the measured qubit. It doesnt really matter if the measured qubit collapses into $\ket{0}$ or $\ket{1}$, but that the state collapses into one of the two. Actually half of the times the state must be measured zero and half it must be measured 1.  So for me the important part of the execution of circuit is that during the circuit, or atleast as the second to last operation, the state is collapsed into one of the two states of the measured qubit.

What I personally dont understand is what qml.measure() does and how it works. I would expect it to collapse a state that is measured and that the qubit could be continued to be used in the circuit with its new state being ofcourse the measured state. 

Lastly i wanted to ask if you believe, after maybe getting some idea of the needs of the algorithm, how i could implement this procedure with current capabilities of pennylane. One way i see how to work around that would be, since i ultimatively use a Hadamard test to get the expectation value of an Observable. Instead of measuring the expectation value of the Observalbe by getting the expectation value of the PauliZ operator on the qubit of the Hadamard test $\bra{\Psi} M \ket{\Psi} $ = P($\ket{0}$) - P($\ket{1}$) = qml.PauliZ(0), I could just measure only the Hadamard Test qubit **together** with the qubit that was in question to be measured. Through this I can know the  state that the qubit in question collapsed in into and for each of the two cases, with the measurement of the Hadamard Test qubit i can calculate the expectation value qml.PauliZ(0) = P($\ket{0}$) - P($\ket{1}$).  Thereby, would a solution be to get qml.counts(wires=[Hadamard_Test, has_to_be_collapsed_qubit])? Or do you think there are other workarounds with qml.measure().

Thank you for your time and patience, i hope this wasn't too long. I appreciate greatly your input. :)

**Comment by trbromley** [comment]
Hi @CLEconomides!

I'll explain `qml.measure()` a little bit more as I think it can achieve what you need if you don't require postselection.
When you do `qml.measure()` on a wire, instead of picking/postselecting on the state $|0\rangle$ or $|1\rangle$, PennyLane actually monitors _both_ branches. If you calculate an expectation value of an observable on another wire, the result will be an average over the expectation values for the $|0\rangle$ and the $|1\rangle$ branch. What we'll be adding to PennyLane in a future release is support for you to be able to actively postselect on one of those branches.

Would you be able to share a few more details about what circuit you are planning to run _after_ the mid-circuit measurement has taken place? For example, are you calculating expectation values, returning states?
