### ISSUE TITLE
support adjoint_metric_tensor for "default.mixed" device

### ISSUE THREAD

**Issue by iridescent0923** [PennyLaneAI/pennylane#4587]
### Feature details

What I wanted to do was: 
1. Define q-node with custom density matrix(= mixed-states)
2. Put it into qml.qinfo.classical_fisher() to calculate classical fisher information.
(Check additional information section)

But, when I define q-node using the custom density matrix with "default.qubit" device, I got the following:
DeviceError: Gate QubitDensityMatrix not supported on device default.qubit.autograd

With "defualt.mixed" device, according to the following document: [qml.adjoint_metric_tensor](https://docs.pennylane.ai/en/latest/code/api/pennylane.adjoint_metric_tensor.html)
"Currently only "default.qubit" with shots=None is supported."

So, is there any possible method to compute classical fisher information using qml.qinfo.classical_fisher() with custom density matrix(= mixed-states) "default.mixed" device?

Thanks.

### How important would you say this feature is?

2: Somewhat important. Needed this quarter.

### Additional information

Original problems I had: [stackexchange](https://quantumcomputing.stackexchange.com/questions/34065/create-qnode-with-density-matrix-on-pennylane/34095#34095)

**Comment by tnemoz** [comment]
Hey there, I'm the one that answered OP's answer on StackExchange.

My previous answer mistakenly read `classical_fisher` for `quantum_fisher`, hence the confusion. However, if we replace `classical_fisher` by `quantum_fisher` in OP's issue, I think it's still a valid issue: it seems that it's not possible to compute the Quantum Fisher information for a mixed state  because of the reasons described above.

Sorry for the confusion, it's on me!

**Comment by iridescent0923** [comment]
>  Thanks for letting me know!

**Comment by iridescent0923** [comment]
I just changed "defualt.qubit" -> "default.mixed" and it works good! Thanks
