### ISSUE TITLE
Include unit tests for auxiliary methods of BaseQnode

### ISSUE THREAD

**Issue by antalszava** [PennyLaneAI/pennylane#506]
#### Issue description

Following up on the https://github.com/XanaduAI/qml/issues/36 issue, the output of the object created at https://github.com/XanaduAI/pennylane/blob/719e27c7d046e7d488b8c68685fe803f4f5afa9f/pennylane/qnodes/base.py#L429 was outputted. In this case, the signature of the method inspected is `def circuit(gammas, betas, edge=None, n_layers=1)`.

* *Expected behavior:* (What you expect to happen)
The keyword arguments are stored in the `kwarg_vars` attribute after calling `_make_variables`.

* *Actual behavior:* (What actually happens)
No keyword arguments were stored in the `kwarg_vars` attribute after calling `_make_variables`.

This might be connected to the keywordarguments be interpreted as regular arguments by `inspect`:
`kwonlyargs FullArgSpec(args=['gammas', 'betas', 'edge', 'n_layers'], varargs=None, varkw=None, defaults=(None, 1), kwonlyargs=[], kwonlydefaults=None, annotations={})`
Further description can be found at: 
https://stackoverflow.com/questions/26963319/python-inspect-module-keyword-only-args

Apart from solving this issue, additional unit tests for `_make_variables` where arguments and keyword arguments are both included would potentially cover this and further issues.

Furthermore, unit tests for `_determine_structured_variable_name` would also be required for coverage.

**Comment by smite** [comment]
> This might be connected to the keywordarguments be interpreted as regular arguments by inspect

It's not an interpretation, it's how different kinds of function parameters are defined in Python.
https://docs.python.org/3.7/library/inspect.html#inspect.Parameter.kind

Specifically, there are no "keyword arguments" in a function signature. Instead there are POSITIONAL_OR_KEYWORD, KEYWORD_ONLY and VAR_KEYWORD parameters, all of which can be inputted using the `keyword=value` syntax.

On the other hand, the quantum functions in PL categorize the parameters in their signature in a different way: "positional" parameters are exactly those that have no default value in the signature, and "auxiliary" parameters are those that do have a default value. "positional" parameters *must* always be given positionally when the qnode is called, and "auxiliary" parameters *must* be given using the keyword=value syntax. IMO this is not a good system, since it conflates two different concepts (input syntax and the existence of a default value).

Anyway, when a qnode is called, the "positional" params are supposed to end up in `args`, and the "auxiliary" params in `kwargs`.

**Comment by smite** [comment]
I think the logic in `BaseQNode._make_variables` (and  maybe `BaseQNode._determine_structured_variable_name`) needs to be partially rethought to solve #505, so I'd postpone adding any unit tests until this is done.

**Comment by antalszava** [comment]
Thanks for the description and the links @smite, it's really helpful! Overall the focus of this issue would rather be to mend the functionality of `_make_variables`. As far as my understanding goes, the `kwargs` provided to  `_make_variables` would eventually still be included either in the `arg_vars` 
 or `kwarg_vars` returned. Currently, this seems not to be the case with the signature in the original description provided, therefore it might be worth revisiting the logic and adding a unit test for this.

As mentioned in #505, that PR would rather provide a cover for most use cases. A further and more extensive logic should follow later (in lines of solving this issue and #507).

**Comment by josh146** [comment]
This is no longer a bug that needs fixing, it light of the [extensive tape-mode refactor](https://pennylane.readthedocs.io/en/latest/code/qml_tape.html). As a result, there are no longer any restrictions on QNode signatures; they follow the same logic and behave exactly as python functions. Closing this for now.
