### ISSUE TITLE
[BUG] Cannot run qnode with sum that contains `I()` (Identity with empty wires)

### ISSUE THREAD

**Issue by Qottmann** [PennyLaneAI/pennylane#5532]
Getting an error for a `Sum` containing `I()`, despite https://github.com/PennyLaneAI/pennylane/pull/5414

```python
dev = qml.device("default.qubit")

h = qml.dot([0.5, 0.5], [qml.I(), qml.X(0)])
assert isinstance(h, qml.ops.Sum)

@qml.qnode(dev)
def qnode():
    return qml.expval(h)

qnode()
```

```pycon
File ~/Xanadu/pennylane/pennylane/measurements/measurements.py:174, in MeasurementProcess.__init__(self, obs, wires, eigvals, id)
    172 if wires is not None:
    173     if len(wires) == 0:
--> 174         raise ValueError("Cannot set an empty list of wires.")
    175     if obs is not None:
    176         raise ValueError("Cannot set the wires if an observable is provided.")

ValueError: Cannot set an empty list of wires.
```

**Comment by Tarun-Kumar07** [comment]
Hey @Qottmann,

I'm fairly new to PennyLane. Would it be okay for me to take a shot at fixing this bug?

**Comment by trbromley** [comment]
Thanks @Tarun-Kumar07! We definitely appreciate your help from previous PRs :rocket: 

This bug is due to a major push we have had for 0.36 to have updated operator arithmetic. We'll need to prioritize fixing this over the next few days in preparation for the release on May 7th.

With the time sensitivity in mind, this bug might not be the best one to take on, unless you have some time over the next few days and we have already identified how to fix this. What do you think @Qottmann?.

**Comment by Tarun-Kumar07** [comment]
Hey @trbromley, thanks for the update.

Given my new status and the urgency of the situation, I might not fully grasp the implications of the major push for 0.36. Tackling this bug alone could be challenging for me. However, if it's a simple fix, I'm eager to help. 
Otherwise, if you could suggest another issue where I could assist, I'd be happy to pitch in.

**Comment by Qottmann** [comment]
I dont have a quick fix on my sleeve, but I also didnt work on the original issue

**Comment by astralcai** [comment]
I would work after you put a `sum_expand` transform on, after https://github.com/PennyLaneAI/pennylane/pull/5543

**Comment by astralcai** [comment]
This is not just `Sum`, it breaks for `Prod` and `SProd` as well:

```
@qml.qnode(dev)
def circuit():
    return qml.expval(qml.prod(qml.PauliZ(0), qml.I()))

circuit()
```
will produce 
```
ValueError: cannot convert float NaN to integer
```
and 
```
@qml.qnode(dev)
def qnode():
    return qml.expval(qml.s_prod(0.1, qml.I()))

qnode()
```
will produce 
```
ValueError: Cannot set an empty list of wires.
```
same as with `Sum`.
