### ISSUE TITLE
[BUG] `QuantumScript.map_to_standard_wires` sometimes returns original tape

### ISSUE THREAD

**Issue by mudit2812** [PennyLaneAI/pennylane#5731]
### Expected behavior

I expect `QuantumScript.map_to_standard_wires` to always return a new tape

### Actual behavior

If the tape wires are in the range $[0, num wires)$, the original tape is returned. This can have repercussions if both the old and new tape exist and the new tape is mutated, as that will cause the original tape to be mutated as well.

### Source code

```shell
import pennylane as qml
from pennylane.tape import QuantumScript

tape1 = QuantumScript([qml.X(0)], [qml.sample(wires=[0, 1])], shots=10)
tape2 = QuantumScript([qml.X(0), qml.Z(2)], [qml.sample(wires=[0, 1])], shots=10)

new_tape1 = tape1.map_to_standard_wires()
new_tape2 = tape2.map_to_standard_wires()

new_tape1._shots = qml.measurements.Shots(20)
new_tape2._shots = qml.measurements.Shots(20)

>>> print(tape1.shots)
Shots(total=20)
>>> print(tape2.shots)
Shots(total=10)
```

### System information

```shell
Dev
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by albi3ro** [comment]
I wouldn't call this bug, but a feature.  We don't want to duplicate things if we don't actually have to duplicated things.

The issue is when we hack mutability into an immutable object. I think we are now just paying the price for that decision.

It may be the time to update our default qubit simulation to pass shots as an independent object through our simulation, instead of relying on `tape.shots`.

**Comment by mudit2812** [comment]
Sounds good. I'm on board with leaving this as is in that case. Closing the issue
