### ISSUE TITLE
Differing behaviour in qml.Optimizers for QAOA tutorial

### ISSUE THREAD

**Issue by milanleonard** [PennyLaneAI/pennylane#788]
I'm trying to benchmark different optimizers for this tutorial (and in general) https://pennylane.ai/qml/demos/tutorial_qaoa_maxcut.html. When I change the optimizer from `qml.AdagradOptimizer` to `qml.QNGOptimizer` I have an issue with the `metric_tensor_fn` where it says it requires a single QNode or VQEObject, however the objective function is not a `qml.qnode`.

![image](https://user-images.githubusercontent.com/1357619/92426913-6fd4de80-f1ce-11ea-96a5-963791b65da2.png)

Trying naively to use the `qml.qnode` wrapper I get a separate error

![image](https://user-images.githubusercontent.com/1357619/92426980-a0b51380-f1ce-11ea-8efa-0eb7798ee1de.png)

Any ideas for how to get around this highly appreciated! 
[meta p.s.] is this type of question better placed here or on the forum?

**Comment by nquesada** [comment]
Hi @milanleonard . Thanks for the report. In the note in the documentation of https://pennylane.readthedocs.io/en/stable/code/api/pennylane.QNGOptimizer.html
you can read a little bit more about how to utilise the quantum natural tensor functionality. It seems like the cost function in the QAOA tutorial is neither a single `QNode` nor a `VQECost`.

**Comment by co9olguy** [comment]
As a bit more explanation, the QNG Optimizer explicitly looks at the variational circuit in order to determine it's parameter update. Thus it only knows what to do with a single QNode. If you have a hybrid computation, there is then a "mixing" of parameters, some coming from the variational circuit, and some (potentially) coming from classical parts of your model, or other QNodes. The QNG optimizer has no update rule for such "extra-circuit" parameters.

**Comment by milanleonard** [comment]
@co9olguy Thanks for the extra info. There's no extra-circuit parameters per se but I'm still struggling to remap this circuit into a single QNode object (which should definitely be possible). In particular I keep running into the issue that I can't act on the computation of the measurement within the QNode, since (I think) it is lazily evaluated when QNode.evaluate() (or __call__) is executed, which means I can't write something like
```
neg_obj = sum([-0.5*(1-qml.expval(qml.Hermitian(pauli_z_2, wires=edge))) for edge in edges])
        return neg_obj
```
And if I try to run this I get an error `TypeError: unsupported operand type(s) for -: 'int' and 'Hermitian'`. I cannot figure out how to get around writing this as a single QNode object, in that it naturally feels like it wants me to qml.map over the template for the collection of expval observables, but I can't do that if I want to use QNG. Is there any way to force those expvals to return the values, or do you have any suggestions as to how I might (even if it's janky) get around this.

**Comment by josh146** [comment]
Hi @milanleonard, depending on how you've structured your cost function, there is a potential work around.

Say you have a cost function consisting of multiple QNodes, and each QNode has

1. the same circuit structure, 
2. the same parameter input, and 
3. there is no 'mixing' of the parameters with classical processing (as @co9olguy has mentioned).

Then, you can take advantage of the fact that [`QNGOptimizer.step`](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.QNGOptimizer.html#pennylane.QNGOptimizer.step) accepts an optional `metric_tensor_fn` argument, where you can pass the explicit metric tensor function you wish the optimizer to use. This avoids the need for the optimizer to 'inspect' the cost function directly to determine the metric tensor function itself.

For example, consider a very basic VQE example:

```python
def circuit(params, **kwargs):
    qml.RX(params[0], wires=0)
    qml.RY(params[1], wires=1)
    qml.CNOT(wires=[0, 1])

dev = qml.device("default.qubit", wires=2)
obs_list = [qml.PauliZ(0) @ qml.PauliZ(1), qml.PauliZ(0) @ qml.PauliZ(1)]
qnodes = qml.map(circuit, obs_list, dev)
```

Our cost function will simply be some linear combination of the QNodes:

```python
def cost(params):
    return np.array([0.2, -0.5]) @ qnodes(params)
```

Since this cost function satisfies our requires above, we can simply pass the metric tensor function of the first QNode to the optimizer:

```python
params = np.array([0.1, 0.2])
opt = qml.QNGOptimizer(0.01)
for i in range(100):
    params = opt.step(cost, params, metric_tensor_fn=qnodes[0].metric_tensor)
```

**Comment by milanleonard** [comment]
Thanks @josh146 that's perfect. Looks like the custom metric tensor argument has come in handy a few times
