### ISSUE TITLE
Classically conditioned gates support

### ISSUE THREAD

**Issue by aswanthkrishna** [PennyLaneAI/pennylane#802]
Is it possible to perform classically conditioned gates,
for example in openqasm 
`measure q[0] -> c[0];
if (c==0) z q[0];`

**Comment by co9olguy** [comment]
Hi @aswanthkrishna, 

This behaviour is currently not supported in PennyLane. 

It's something we could think about implementing in the future. However, it is not clear that it plays well with the automatic differentiation which is the core feature of the library (because you can't usually compute a gradient of a conditioning step), so depending on your use-case, it may or may not be of value to have this in the library.

**Comment by albi3ro** [comment]
We now support mid circuit measurements in PL.  See [`qml.measure`](https://docs.pennylane.ai/en/stable/code/api/pennylane.measure.html?highlight=measure) and [`qml.cond`](https://docs.pennylane.ai/en/stable/code/api/pennylane.cond.html?highlight=cond).
