### ISSUE TITLE
Higher order derivatives

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#890]
I was hoping that PennyLane could automatically compute higher order derivatives, especially the Hessian matrix (and I think I remember that this used to work in the past).

A minimal example that I thought should produce the Hessian matrix of a Qnode is the followig:
```
import pennylane as qml
import numpy as np

dev = qml.device('default.qubit', wires=1)

@qml.qnode(dev)
def cost(params):
    qml.RY(params[0], wires=0)
    qml.RX(params[1], wires=0)
    return qml.expval(qml.PauliZ(0))

params = np.array([0.1, 0.2])

print(qml.jacobian(qml.jacobian(cost, argnum=0), argnum=0)(params))
```
Instead I am getting:
```
[...]
  File "../python3.8/site-packages/pennylane/utils.py", line 165, in _unflatten
    raise TypeError("Unsupported type in the model: {}".format(type(model)))
TypeError: Unsupported type in the model: <class 'autograd.builtins.SequenceBox'>
```
Is there some fundamental reason why this can't work is it just that `_flatten()` and `unflatten()` need to have their functionality slightly extended?

**Comment by antalszava** [comment]
Hi @cvjjm,

The custom gradient defined for `qml.jacobian` has parts which are non-differentiable when using `default.qubit`. That's the reason for experiencing the error, the gradient that is returned cannot be differentiated another time.

One approach here could be to use the `default.qubit.autograd` device where end-to-end differentiability is preserved:
```python
import pennylane as qml
import numpy as np

dev = qml.device('default.qubit.autograd', wires=1)

@qml.qnode(dev)
def cost(params):
    qml.RY(params[0], wires=0)
    qml.RX(params[1], wires=0)
    return qml.expval(qml.PauliZ(0))

params = np.array([0.1, 0.2])

print(qml.jacobian(qml.jacobian(cost, argnum=0), argnum=0)(params))
```

**Comment by cvjjm** [comment]
But it is obvious what PennyLane should be doing in my example (apply the parameter shift rule twice) and this should work not just on end-to-end differentiable devices but independently of the device and in particular also on hardware devices.

I would consider this a bug.

At first sight it looks like error I posted above is caused by flatten/unflatten not handling autograd objects correctly. Or is there a deeper reason for why this functionality cannot be provided?

**Comment by co9olguy** [comment]
Hi @cvjjm, thanks for your interest! This feature is definitely on our radar and definitely doable. It's not something we claim to support currently, so not really a bug, but more a feature request.

For a bit of context, one thing that's held us back slightly is that supporting higher-order derivatives would (currently) require hand-coding this functionality for each derivative object you'd like to do. For the Hessian, it certainly makes sense to do the hand-coding, since it's a commonly-known quantity (this is an item in our backlog). 

In order to support arbitrary higher order derivatives though, it would be much more useful if the results of, e.g., `qml.jacobian()`, were composable automatically. So PennyLane would know to apply a parameter-shift rule to an input, even if that input itself is already the result of applying earlier parameter-shift rules.

We've been thinking about how we can support this more generally, but admittedly it has been difficult to support arbitrary derivatives because the different ML interfaces don't quite provide the flexibility we'd like to make this as full-featured as we might like.

**Comment by cvjjm** [comment]
I agree that "bug" is too strong a word. But for a person with knowledge of autograd it is a natural expectation that pennylane.jacobian() would itself be differentiable again.

After a superficial look at the code, it seems to me that the easiest way to make pennylane.jacbobian() return something differentiable would be to have it return a qml.sum() of a QNodeCollection instead of doing the evaluation and summation resulting from the paramter shif rule "manually" in _pd_analytic().

**Comment by co9olguy** [comment]
Maybe @josh146 can offer his thoughts here. I know he's dug the most into these questions and the gotchas of implementing in a way that can be supported on all of autograd, tf, and pytorch.

He's not available this week, but could give some more info when available

**Comment by josh146** [comment]
Hi @cvjjm! As Nathan and Antal have mentioned above, the reason why the second derivative doesn't work is because the gradient computation is performed using calls _outside_ of the (wrapped) NumPy provided by Autograd, that supports autodifferentiation. This is by necessity; to evaluate the gradient, we are making calls to a quantum device --- we can not evaluate the gradient solely by calling `autograd.numpy`.

For example, consider the following Autograd custom gradient example, adapted from the [TensorFlow documentation](https://www.tensorflow.org/api_docs/python/tf/custom_gradient):

```python
import autograd
import numpy as onp

@autograd.extend.primitive
def log1pexp(x):
    # we define this function using
    # non-differentiable (vanilla) NumPy
    return onp.log(1 + onp.exp(x))

def vjp(ans, x):
    def grad(dy):
        # we define the vector jacobian product function using
        # non-differentiable (vanilla) NumPy
        return dy * (1 - 1 / (1 + onp.exp(x)))
    return grad

autograd.extend.defvjp(log1pexp, vjp, argnums=[0])
```

Here, we are defining the gradient using the **non-differentiable** standard NumPy, _not_ the end-to-end differentiable wrapped `autograd.numpy` module. This is analogous to how we call external, non-differentiable quantum devices in PennyLane.

Differentiating this custom function works fine, as our custom `vjp` gradient function is being called:

```pycon
>>> from autograd import numpy as np
>>> grad_fn = autograd.grad(log1pexp)
>>> print(grad_fn(0.5))
0.6224593312018546
```

However, attempting to compute the second derivative will fail, since Autograd does not know how to differentiate `vjp`!

```pycon
>>> grad2_fn = autograd.grad(grad_fn)
>>> print(grad2_fn(0.5))
  File "test3.py", line 14, in grad
    return dy * (1 - 1 / (1 + onp.exp(x)))
TypeError: loop of ufunc does not support argument 0 of type ArrayBox which has no callable exp method
```

To solve this, we have two options:

1. Define the custom gradient using the end-to-end differentiable `autograd.numpy` module instead:

   ```python
   from autograd import numpy as np
   def vjp(ans, x):
      def grad(dy):
         return dy * (1 - 1 / (1 + np.exp(x)))
      return grad
    ```

2. Hand code the second derivative _as well_, using custom gradients.

While option (1) would be preferable (and would allow all nth derivatives to start working), it is not possible in our cases; we can't replace the calls to the quantum devices with calls to `autograd.numpy`!* Instead, we have to go with option (2). As Nathan has mentioned, this is on our roadmap, and we hope to have this implemented soon (across all interfaces).

To finish off the example above, this is how we would hardcode in the second derivative (essentially, we just nest the registration of the custom vjp functions):

```python
@autograd.extend.primitive
def log1pexp(x):
    return onp.log(1 + onp.exp(x))

# mark the first derivative as a primitive as well
@autograd.extend.primitive
def grad1(x, dy):
    return dy * (1 - 1 / (1 + onp.exp(x)))

def vjp(ans, x):  # custom first derivative
    return lambda dy: grad1(x, dy)

def vjp2(ans, x, dy):  # custom second derivative
    def grad2(dy):
        return dy * (1 / (1 + onp.exp(x)) - 1 / ((1 + onp.exp(x)) ** 2))
    return grad2

autograd.extend.defvjp(grad1, vjp2, argnums=[0])
autograd.extend.defvjp(log1pexp, vjp, argnums=[0])
```

The above should now allow second derivatives (but not third derivatives or higher!)

```pycon
>>> grad_fn = autograd.grad(log1pexp)
>>> print(grad_fn(0.5))
0.6224593312018546
>>> grad2_fn = autograd.grad(grad_fn)
>>> print(grad2_fn(0.5))
0.23500371220159447
```

---

\* It might be possible to go with option (1) if Autograd supports a recursive definition of the custom gradient function. I've tried this previously, but ran into errors, so I fear it is not possible. However, if you have any ideas, that would be great.

**Comment by cvjjm** [comment]
Thanks for the very detailed explanation!

I still don't see why at least shift-differentiable cases cannot be supported in a more general/straight forward way as follows:

Instead of doing the substaction of the shifted QNodes in _pd_analytic() "by hand", qml.jacbian() could return a qml.sum() over a QNodeCollection with two QNodes that add/substract the shifts to the original QNode. The QNodeCollection would naturally itself be differentiable again.

This should work independently of the device and for all interfaces.

Is it obvious why this cannot work?

**Comment by co9olguy** [comment]
Hi @cvjjm, 

Your intuition is strong. This is exactly in line with an approach that we have considered. We would love to do things this way. We will continue to think about it, but there are usually some subtleties that emerge from the need to support 3 external autodiff frameworks and calls to quantum computers. Hopefully we can resolve these and provide a full-featured solution.

In the meantime, we have bumped up the priority of specific (hard-coded) higher-order derivatives like the Hessian. We are also planning to update the quantum natural gradient (a form of second-order derivative)

**Comment by josh146** [comment]
Closing this now that Hessian support is built in to PennyLane
