### ISSUE TITLE
Support non-flat output shapes in KerasLayer

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/pennylane#936]
The [KerasLayer](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.qnn.KerasLayer.html) class has an `output_dim` argument to specify the output shape of the layer. Currently, the output shape is assumed to be flat, and if users pass an iterable to `output_dim` then only the first element is selected (see [here](https://github.com/PennyLaneAI/pennylane/blob/432377a2cad9d9a4b9e5ed861385e73d48c725fe/pennylane/qnn/keras.py#L219)).

So far, this approach has worked ok because we expect a flat output from a QNode. However, a `density_matrix()` return type was [recently added](https://github.com/PennyLaneAI/pennylane/pull/878), which provides a non-flat output. One current workaround is to specify `output_dim=length_of_flattened_matrix` and then adding a `tf.keras.layers.Flatten()` layer directly after the `KerasLayer`. However, ideally we should properly support tuples in `output_dim` so that the resulting model can be built correctly.

**Comment by josh146** [comment]
> However, ideally we should properly support tuples in output_dim so that the resulting model can be built correctly.

Would supporting tuple in `output_dim` still require the `Flatten()` layer?

**Comment by trbromley** [comment]
I don't think you *need* the flatten layer, it just depends on what the next layer in the model looks like. If it's, e.g., a dense layer then you can flatten. But maybe we unlock some flexibility to plug into, e.g., convolutional layers.

**Comment by kessler-frost** [comment]
Hi,
I think I am missing something here, why do we need to ask the user about the `output_dim` parameter? There are 3 possible scenarios where our `qnn.KerasLayer` can be put when creating a hybrid neural network:

1. At the beginning as the first layer; classical NNs only require the input shape to be mentioned when creating the first layer of a NN, hence passing the `output_dim` parameter will not help in this case.
2. Somewhere in the whole NN between two layers; let's say the layer next to our `qnn.KerasLayer` is a regular layer from `tf.keras.layers`, since the regular layer automatically determines the output shape of the previous layer and modifies itself accordingly, thus `output_dim` variable will not be used. Say the following layer is also a `qnn.KerasLayer`, then we can implement similar techniques used by regular layers to determine the output dimensions (which will make `qnn.KerasLayer` more similar to regular layers).
3. At the end of the NN; I'm not sure about this, when will we be using a `qnn.KerasLayer` as the last layer in a NN? (sorry, I couldn't think of an example).

As long as we are using Keras for creating the hybrid neural network, in my opinion, `output_dim` is not a necessary parameter to be passed into `qnn.KerasLayer`. Please let me know if I am wrong somewhere as I'm merely a beginner in this field.

Thanks!

**Comment by trbromley** [comment]
Hey @kessler-frost! That's a good point, the output dimension is probably extra information in most cases. Indeed we don't need the output dimension for `TorchLayer`. If I recall correctly, the reason we added `output_dim` for `KerasLayer` was because you need to define the [compute_output_shape](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer#compute_output_shape) method in the Keras `Layer` API - and it wasn't clear how to infer the output dimension from the input dimension with a QNode.

**Comment by kessler-frost** [comment]
Oh, ok. Got it. So what do you think will be the best course of action here? Keeping `output_dim` a passable parameter until we find a way to infer output dimension from input dimensions of a QNode? I would like to work on that if that's the case. Thanks!

**Comment by trbromley** [comment]
Right! One could infer the output dimension by inspecting the circuit measurements or simply by calling the circuit and looking at the output shape (in fact, a similar thing [has been added](https://github.com/PennyLaneAI/pennylane/blob/ac85314167ce312e6786112b4c2de2101ad6c3d2/pennylane/tape/tapes/tape.py#L359)). However, for now I think it's best to keep things explicit and require the `output_dim` argument.

> I would like to work on that if that's the case

Great, we welcome contributions! Supporting non-flat output shapes in KerasLayer should be a great first issue to get started with.
