### ISSUE TITLE
Getting excited states for hydrogen

### ISSUE THREAD

**Issue by knc6** [PennyLaneAI/pennylane#980]
#### Issue description
The ground state energy, E0 is calculated in the https://pennylane.ai/qml/demos/tutorial_vqe.html using VQE. Is it possible to get excited state energies E1 as well? This can help in getting something like eigenspectrum/bandstructure.

**Comment by co9olguy** [comment]
Hi @knc6, thanks for your interest :slightly_smiling_face:. This sounds more like a question for our [discussion forum](https://discuss.pennylane.ai/), rather than an issue with the code/software (which is what our GitHub issues page is used for). Would you be able to ask your question there instead? Thanks!
